project_id = "wcwnyvoezudyxiayyzek"

[functions.validate-replay]
verify_jwt = false

[functions.fetch-jstris-replay]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.keep-alive]
verify_jwt = false
