import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'zh' | 'zh-TW' | 'en' | 'ja' | 'ko' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  zh: {
    // Game related
    'game.title': '俄罗斯方块竞技平台',
    'game.play': '开始游戏',
    'game.singlePlayer': '单人模式',
    'game.multiPlayer': '多人模式',
    'game.ranked': '排位赛',
    'game.sprint40': '40行竞速',
    'game.ultra2min': '2分钟极限',
    'game.endless': '无尽模式',
    'game.freeForAll': '自由对战',
    'game.oneVsOne': '1v1对战',
    'game.customRoom': '自建房间',
    'game.description': '体验最纯粹的俄罗斯方块竞技',
    'game.singlePlayerDesc': '挑战自己的极限，刷新个人记录',
    'game.multiPlayerDesc': '与全球玩家实时对战',
    'game.rankedDesc': '争夺最高段位排名',
    'game.gameOver': '游戏结束',
    'game.newRecord': '新纪录！',
    'game.score': '分数',
    'game.lines': '行数',
    'game.level': '等级',
    'game.time': '时间',
    'game.restart': '重新开始',
    'game.continue': '继续',
    
    // Auth related
    'auth.login': '登录',
    'auth.register': '注册',
    'auth.guest': '游客模式',
    'auth.username': '用户名',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.fillEmailPassword': '请填写邮箱和密码',
    'auth.fillUsername': '请填写用户名',
    'auth.loginError': '登录错误',
    'auth.invalidCredentials': '邮箱或密码错误，请检查后重试',
    'auth.verifyEmail': '请先验证邮箱，检查邮箱中的激活链接',
    'auth.networkError': '网络连接问题，请检查网络后重试',
    'auth.rateLimited': '登录尝试过于频繁，请稍后重试',
    'auth.requestAborted': '请求被中断，请重试',
    'auth.loginSuccess': '登录成功！',
    'auth.registerSuccess': '注册成功！请检查邮箱验证链接',
    'auth.userExists': '用户已存在',
    'auth.checkEmailLink': '请检查邮箱验证链接',
    'auth.registerFailed': '注册失败，请重试',
    'auth.forgotPassword': '忘记密码？',
    'auth.guestLogin': '游客登录',
    'auth.guestLoginFailed': '游客登录失败',
    'auth.guestDescription': '以游客身份快速开始游戏',
    'auth.noAccount': '还没有账户？立即注册',
    'auth.hasAccount': '已有账户？立即登录',
    'auth.processing': '处理中...',
    'auth.loginDesc': '登录您的账户开始游戏',
    'auth.registerDesc': '创建新账户',
    'auth.enterUsername': '请输入用户名',
    'auth.enterEmail': '请输入邮箱地址',
    'auth.enterPassword': '请输入密码',
    'auth.guestSuccess': '访客登录成功',
    'auth.guestRestricted': '访客用户无法参与排位赛和锦标赛',
    
    // Settings related
    'settings.controls': '控制设置',
    'settings.keyboard': '键盘设置',
    'settings.game': '游戏设置',
    'settings.shortcuts': '快捷方式',
    'settings.das': '键盘重复速率',
    'settings.arr': '软降速度',
    'settings.sdf': '瞬降速度',
    'settings.preview': '预设布局',
    'settings.customKeys': '自定义键位',
    'settings.moveLeft': '左移',
    'settings.moveRight': '右移',
    'settings.softDrop': '软降',
    'settings.hardDrop': '硬降',
    'settings.rotateClockwise': '顺时针旋转',
    'settings.rotateCounterclockwise': '逆时针旋转',
    'settings.rotate180': '180°旋转',
    'settings.hold': '暂存',
    'settings.pause': '暂停',
    'settings.keyboardInstructions': '按键映射说明',
    'settings.keyboardTip': '点击按键框然后按下你想要的按键来设置',
    'settings.controlsDesc': '自定义按键和游戏参数',
    'settings.livePreview': '实时预览',
    'settings.testWithKeys': '使用 ← → 键测试手感',
    'settings.maxUndoSteps': '最大撤销步数',
    
    // Room related
    'room.create': '创建房间',
    'room.join': '加入房间',
    'room.share': '分享房间',
    'room.maxPlayers': '最大玩家数',
    'room.needLogin': '需要登录才能创建房间',
    'room.createFailed': '创建房间失败，请重试',
    'room.createSuccess': '房间创建成功！房间号: ',
    'room.joinFailed': '加入房间失败，请检查房间号',
    'room.joinSuccess': '成功加入房间',
    'room.enterCode': '请输入房间号',
    'room.roomFull': '房间已满或不存在',
    'room.alreadyInRoom': '您已经在该房间中',
    'room.activeRooms': '活跃房间',
    'room.onlinePlayers': '在线玩家',
    'room.quickJoin': '快速加入房间',
    'room.enterRoomCode': '输入4位数字房间号',
    'room.joining': '加入中...',
    'room.notExist': '房间不存在或已关闭',
    'room.noActiveRooms': '暂无活跃的房间',
    'room.roomUnavailable': '房间不可用',
    
    // Replay related
    'replay.view': '查看回放',
    'replay.speed': '回放速度',
    'replay.title': '回放系统',
    'replay.description': '观看和分析游戏录像',
    
    // Navigation
    'nav.home': '首页',
    'nav.play': '游戏',
    'nav.multiplayer': '多人游戏',
    'nav.profile': '个人资料',
    'nav.leaderboard': '排行榜',
    'nav.settings': '设置',
    'nav.backToMenu': '返回主菜单',
    
    // Ranking
    'rank.system': '排位系统',
    'rank.current': '当前段位',
    'rank.points': '积分',
    'rank.nextRank': '下一段位',
    'rank.promotion': '还需积分晋级',
    
    // Ads
    'ad.placeholder': '广告位招租中',
    'ad.contact': '联系管理员',
    
    // Income
    'income.donations': '捐赠收入',
    'income.ads': '广告收入',
    'income.total': '总收入',
    
    // Admin
    'admin.panel': '管理后台',
    'admin.income': '收入系统',
    'admin.title': '后台管理',
    'admin.description': '广告和收入管理',
    'admin.adManagement': '广告管理系统',
    'admin.createAd': '创建广告',
    'admin.editAd': '编辑广告',
    'admin.adTitle': '广告标题',
    'admin.adContent': '广告内容',
    'admin.adImage': '广告图片',
    'admin.adPosition': '广告位置',
    'admin.position.left': '左侧',
    'admin.position.right': '右侧',
    'admin.position.top': '顶部',
    'admin.position.bottom': '底部',
    'admin.position.popup': '弹窗',
    'admin.priority': '优先级',
    'admin.targetRegion': '目标地区',
    'admin.targetLanguage': '目标语言',
    'admin.startDate': '开始日期',
    'admin.endDate': '结束日期',
    'admin.budget': '预算',
    'admin.frequencyCap': '频次上限',
    'admin.targetUrl': '点击跳转URL',
    'admin.abTestGroup': 'A/B测试分组',
    'admin.enableNow': '立即启用',
    'admin.cancel': '取消',
    'admin.update': '更新',
    'admin.create': '创建',
    'admin.adList': '广告列表',
    'admin.analytics': '数据分析',
    'admin.operationLogs': '操作日志',
    'admin.allAds': '所有广告',
    'admin.status': '状态',
    'admin.impressionsClicks': '展示/点击',
    'admin.budgetSpent': '预算/支出',
    'admin.actions': '操作',
    'admin.active': '活跃',
    'admin.disabled': '停用',
    'admin.loadFailed': '加载广告失败',
    'admin.saveFailed': '保存广告失败',
    'admin.updateSuccess': '广告更新成功',
    'admin.createSuccess': '广告创建成功',
    'admin.enableSuccess': '广告已启用',
    'admin.disableSuccess': '广告已停用',
    'admin.deleteConfirm': '确定要删除这个广告吗？',
    'admin.deleteSuccess': '广告删除成功',
    'admin.deleteFailed': '删除失败',
    'admin.noPermission': '无权限',
    'admin.noAccess': '无权限访问',
    'admin.loading': '加载中...',
    
    // Common
    'common.welcome': '欢迎回来',
    'common.guestMode': '游客模式',
    'common.needLogin': '需要登录',
    'common.startMatch': '开始匹配',
    'common.startRank': '开始排位',
    'common.backToHome': '返回首页',
    'common.openSettings': '打开游戏设置',
    'common.enter': '进入',
    'common.back': '返回',
    'common.copyright': '基于现代俄罗斯方块规则',
    'common.confirm': '确认',
    'common.delete': '删除',
    'common.save': '保存',
    'common.close': '关闭',
    'common.success': '成功',
    'common.failed': '失败',
    'common.retry': '重试',
    'common.creating': '创建中...',
    'common.loading': '加载中...',
    'common.comingSoon': '即将推出',
    'common.registeredUser': '注册用户',
    'common.guestUser': '访客用户',
    'common.loadStatsFailed': '加载统计失败',
    'common.networkError': '网络连接错误',
    'common.modeFailed': '模式选择失败，请重试',
    
    // Tutorial
    'tutorial.title': '游戏教程',
    'tutorial.description': '学习高级技巧和策略',
    
    // Team Battle
    'teamBattle.title': '团战模式',
    'teamBattle.entryDesc': '2v2/3v3/4v4 团队对战，支持三种垃圾分配策略',
    'teamBattle.createRoom': '创建团战房间',
    'teamBattle.joinRoom': '加入房间',
    'teamBattle.activeRooms': '活跃房间',
    'teamBattle.strategy.focus': '集中打击',
    'teamBattle.strategy.random': '随机分配',
    'teamBattle.strategy.even': '平均分配',
    'teamBattle.tabHint': '对局中按 Tab 键切换垃圾分配策略',
    'teamBattle.teamSize': '团队规模',
    'teamBattle.garbageStrategy': '垃圾行分配策略',
    'teamBattle.focusDesc': '集中打击 - 垃圾行发送给对方APM最高的玩家',
    'teamBattle.randomDesc': '随机分配 - 垃圾行随机发送给对方任意玩家',
    'teamBattle.evenDesc': '平均分配 - 垃圾行平均分配给对方所有玩家',
    'teamBattle.unknownStrategy': '未知策略',
    'teamBattle.createSuccess': '团战房间创建成功！房间码: ',
    'teamBattle.joinSuccess': '成功加入团战房间！',
    'teamBattle.noActiveRooms': '暂无活跃的团战房间',
    'teamBattle.enter4DigitCode': '输入4位房间码',
    'teamBattle.setTeamAndStrategy': '设置团队规模和垃圾行策略',
    'teamBattle.2v2': '2v2 (4人对战)',
    'teamBattle.3v3': '3v3 (6人对战)',
    'teamBattle.4v4': '4v4 (8人对战)',
    'teamBattle.2v2v2v2': '2v2/3v3/4v4 团队对战',
    
    // Multiplayer
    'multiplayer.title': '多人游戏',
    'multiplayer.1v1': '1v1 对战',
    'multiplayer.1v1Desc': '经典一对一俄罗斯方块对战',
    'multiplayer.ranked': '排位赛',
    'multiplayer.rankedDesc': '参与排位匹配，提升段位',
    'multiplayer.customRoom': '自定义房间',
    'multiplayer.customRoomDesc': '创建或加入自定义对战房间',
    'multiplayer.battleRoyale': '大逃杀模式',
    'multiplayer.battleRoyaleDesc': '多人混战，最后一人获胜',
    'multiplayer.botRoom': 'AI 机器人对战',
    'multiplayer.botRoomDesc': '与不同难度的 AI 机器人对战',
    'multiplayer.needLoginMulti': '需要登录才能进行多人游戏',
    'multiplayer.quickLogin': '访客快速登录',
    
    // Bot Room
    'bot.createRoom': '创建Bot房间',
    'bot.createRoomDesc': '创建一个专门的Bot房间，可以添加不同难度的AI机器人进行对战练习',
    'bot.availableRooms': '可用的Bot房间',
    'bot.noRooms': '暂无可用的Bot房间',
    'bot.aboutRooms': '关于Bot房间',
    'bot.aboutDesc1': 'Bot房间是专门与AI机器人对战的游戏模式',
    'bot.aboutDesc2': '房间中的Bot显示为红色方块，易于识别',
    'bot.aboutDesc3': '支持4种不同难度的Bot：简单、中等、困难、专家',
    'bot.aboutDesc4': '可以同时与多个Bot和真实玩家一起游戏',
    'bot.aboutDesc5': '适合练习技巧和挑战更高难度',
    'bot.room': 'Bot房间',
    'bot.connected': '已连接',
    'bot.connecting': '连接中...',
    'bot.startGame': '开始游戏',
    'bot.creator': '创建者',
    'bot.players': '玩家',
    
    // Game Mode Selector
    'mode.select': '选择游戏模式',
    'mode.backToMain': '返回主菜单',
    'mode.target': '目标',
    'mode.timeLimit': '时限',
    'mode.unlimited': '无限制游戏',
    'mode.startGame': '开始游戏',
    'mode.timed': '限时',
    'mode.sprint': '冲刺',
    'mode.targetLines': '目标: {lines} 行',
    'mode.timeLimitFormat': '时限: {time}',
    'mode.clearLines': '目标: 清除 {lines} 行'
  },
  
  'zh-TW': {
    // Game related
    'game.title': '俄羅斯方塊競技平台',
    'game.play': '開始遊戲',
    'game.singlePlayer': '單人模式',
    'game.multiPlayer': '多人模式',
    'game.ranked': '排位賽',
    'game.sprint40': '40行競速',
    'game.ultra2min': '2分鐘極限',
    'game.endless': '無盡模式',
    'game.freeForAll': '自由對戰',
    'game.oneVsOne': '1v1對戰',
    'game.customRoom': '自建房間',
    'game.description': '體驗最純粹的俄羅斯方塊競技',
    'game.singlePlayerDesc': '挑戰自己的極限，刷新個人記錄',
    'game.multiPlayerDesc': '與全球玩家實時對戰',
    'game.rankedDesc': '爭奪最高段位排名',
    'game.gameOver': '遊戲結束',
    'game.newRecord': '新紀錄！',
    'game.score': '分數',
    'game.lines': '行數',
    'game.level': '等級',
    'game.time': '時間',
    'game.restart': '重新開始',
    'game.continue': '繼續',
    
    // Auth related
    'auth.login': '登入',
    'auth.register': '註冊',
    'auth.guest': '訪客模式',
    'auth.username': '用戶名',
    'auth.email': '郵箱',
    'auth.password': '密碼',
    'auth.fillEmailPassword': '請填寫郵箱和密碼',
    'auth.fillUsername': '請填寫用戶名',
    'auth.loginError': '登入錯誤',
    'auth.invalidCredentials': '郵箱或密碼錯誤，請檢查後重試',
    'auth.verifyEmail': '請先驗證郵箱，檢查郵箱中的激活鏈接',
    'auth.networkError': '網絡連接問題，請檢查網絡後重試',
    'auth.rateLimited': '登入嘗試過於頻繁，請稍後重試',
    'auth.requestAborted': '請求被中斷，請重試',
    'auth.loginSuccess': '登入成功！',
    'auth.registerSuccess': '註冊成功！請檢查郵箱驗證鏈接',
    'auth.userExists': '用戶已存在',
    'auth.checkEmailLink': '請檢查郵箱驗證鏈接',
    'auth.registerFailed': '註冊失敗，請重試',
    'auth.forgotPassword': '忘記密碼？',
    'auth.guestLogin': '訪客登入',
    'auth.guestLoginFailed': '訪客登入失敗',
    'auth.guestDescription': '以訪客身份快速開始遊戲',
    'auth.noAccount': '還沒有帳戶？立即註冊',
    'auth.hasAccount': '已有帳戶？立即登入',
    'auth.processing': '處理中...',
    'auth.loginDesc': '登入您的帳戶開始遊戲',
    'auth.registerDesc': '創建新帳戶',
    'auth.enterUsername': '請輸入用戶名',
    'auth.enterEmail': '請輸入郵箱地址',
    'auth.enterPassword': '請輸入密碼',
    'auth.guestSuccess': '訪客登入成功',
    'auth.guestRestricted': '訪客用戶無法參與排位賽和錦標賽',
    
    // Settings related
    'settings.controls': '控制設定',
    'settings.keyboard': '鍵盤設定',
    'settings.game': '遊戲設定',
    'settings.shortcuts': '快捷方式',
    'settings.das': '鍵盤重複速率',
    'settings.arr': '軟降速度',
    'settings.sdf': '瞬降速度',
    'settings.preview': '預設佈局',
    'settings.customKeys': '自定義鍵位',
    'settings.moveLeft': '左移',
    'settings.moveRight': '右移',
    'settings.softDrop': '軟降',
    'settings.hardDrop': '硬降',
    'settings.rotateClockwise': '順時針旋轉',
    'settings.rotateCounterclockwise': '逆時針旋轉',
    'settings.rotate180': '180°旋轉',
    'settings.hold': '暫存',
    'settings.pause': '暫停',
    'settings.keyboardInstructions': '按鍵映射說明',
    'settings.keyboardTip': '點擊按鍵框然後按下你想要的按鍵來設定',
    'settings.controlsDesc': '自定義按鍵和遊戲參數',
    'settings.livePreview': '即時預覽',
    'settings.testWithKeys': '使用 ← → 鍵測試手感',
    'settings.maxUndoSteps': '最大撤銷步數',
    
    // Room related
    'room.create': '創建房間',
    'room.join': '加入房間',
    'room.share': '分享房間',
    'room.maxPlayers': '最大玩家數',
    'room.needLogin': '需要登入才能創建房間',
    'room.createFailed': '創建房間失敗，請重試',
    'room.createSuccess': '房間創建成功！房間號: ',
    'room.joinFailed': '加入房間失敗，請檢查房間號',
    'room.joinSuccess': '成功加入房間',
    'room.enterCode': '請輸入房間號',
    'room.roomFull': '房間已滿或不存在',
    'room.alreadyInRoom': '您已經在該房間中',
    'room.activeRooms': '活躍房間',
    'room.onlinePlayers': '在線玩家',
    'room.quickJoin': '快速加入房間',
    'room.enterRoomCode': '輸入4位數字房間號',
    'room.joining': '加入中...',
    'room.notExist': '房間不存在或已關閉',
    'room.noActiveRooms': '暫無活躍的房間',
    'room.roomUnavailable': '房間不可用',
    
    // Replay related
    'replay.view': '查看回放',
    'replay.speed': '回放速度',
    'replay.title': '回放系統',
    'replay.description': '觀看和分析遊戲錄像',
    
    // Navigation
    'nav.home': '首頁',
    'nav.play': '遊戲',
    'nav.multiplayer': '多人遊戲',
    'nav.profile': '個人資料',
    'nav.leaderboard': '排行榜',
    'nav.settings': '設定',
    'nav.backToMenu': '返回主選單',
    
    // Ranking
    'rank.system': '排位系統',
    'rank.current': '當前段位',
    'rank.points': '積分',
    'rank.nextRank': '下一段位',
    'rank.promotion': '還需積分晉級',
    
    // Ads
    'ad.placeholder': '廣告位招租中',
    'ad.contact': '聯繫管理員',
    
    // Income
    'income.donations': '捐贈收入',
    'income.ads': '廣告收入',
    'income.total': '總收入',
    
    // Admin
    'admin.panel': '管理後台',
    'admin.income': '收入系統',
    'admin.title': '後台管理',
    'admin.description': '廣告和收入管理',
    'admin.adManagement': '廣告管理系統',
    'admin.createAd': '創建廣告',
    'admin.editAd': '編輯廣告',
    'admin.adTitle': '廣告標題',
    'admin.adContent': '廣告內容',
    'admin.adImage': '廣告圖片',
    'admin.adPosition': '廣告位置',
    'admin.position.left': '左側',
    'admin.position.right': '右側',
    'admin.position.top': '頂部',
    'admin.position.bottom': '底部',
    'admin.position.popup': '彈窗',
    'admin.priority': '優先級',
    'admin.targetRegion': '目標地區',
    'admin.targetLanguage': '目標語言',
    'admin.startDate': '開始日期',
    'admin.endDate': '結束日期',
    'admin.budget': '預算',
    'admin.frequencyCap': '頻次上限',
    'admin.targetUrl': '點擊跳轉URL',
    'admin.abTestGroup': 'A/B測試分組',
    'admin.enableNow': '立即啟用',
    'admin.cancel': '取消',
    'admin.update': '更新',
    'admin.create': '創建',
    'admin.adList': '廣告列表',
    'admin.analytics': '數據分析',
    'admin.operationLogs': '操作日誌',
    'admin.allAds': '所有廣告',
    'admin.status': '狀態',
    'admin.impressionsClicks': '展示/點擊',
    'admin.budgetSpent': '預算/支出',
    'admin.actions': '操作',
    'admin.active': '活躍',
    'admin.disabled': '停用',
    'admin.loadFailed': '載入廣告失敗',
    'admin.saveFailed': '保存廣告失敗',
    'admin.updateSuccess': '廣告更新成功',
    'admin.createSuccess': '廣告創建成功',
    'admin.enableSuccess': '廣告已啟用',
    'admin.disableSuccess': '廣告已停用',
    'admin.deleteConfirm': '確定要刪除這個廣告嗎？',
    'admin.deleteSuccess': '廣告刪除成功',
    'admin.deleteFailed': '刪除失敗',
    'admin.noPermission': '無權限',
    'admin.noAccess': '無權限訪問',
    'admin.loading': '載入中...',
    
    // Common
    'common.welcome': '歡迎回來',
    'common.guestMode': '訪客模式',
    'common.needLogin': '需要登入',
    'common.startMatch': '開始匹配',
    'common.startRank': '開始排位',
    'common.backToHome': '返回首頁',
    'common.openSettings': '打開遊戲設定',
    'common.enter': '進入',
    'common.back': '返回',
    'common.copyright': '基於現代俄羅斯方塊規則',
    'common.confirm': '確認',
    'common.delete': '刪除',
    'common.save': '保存',
    'common.close': '關閉',
    'common.success': '成功',
    'common.failed': '失敗',
    'common.retry': '重試',
    'common.creating': '創建中...',
    'common.loading': '載入中...',
    'common.comingSoon': '即將推出',
    'common.registeredUser': '註冊用戶',
    'common.guestUser': '訪客用戶',
    'common.loadStatsFailed': '載入統計失敗',
    'common.networkError': '網絡連接錯誤',
    'common.modeFailed': '模式選擇失敗，請重試',
    
    // Tutorial
    'tutorial.title': '遊戲教程',
    'tutorial.description': '學習高級技巧和策略',
    
    // Team Battle
    'teamBattle.title': '團戰模式',
    'teamBattle.entryDesc': '2v2/3v3/4v4 團隊對戰，支持三種垃圾分配策略',
    'teamBattle.createRoom': '創建團戰房間',
    'teamBattle.joinRoom': '加入房間',
    'teamBattle.activeRooms': '活躍房間',
    'teamBattle.strategy.focus': '集中打擊',
    'teamBattle.strategy.random': '隨機分配',
    'teamBattle.strategy.even': '平均分配',
    'teamBattle.tabHint': '對局中按 Tab 鍵切換垃圾分配策略',
    'teamBattle.teamSize': '團隊規模',
    'teamBattle.garbageStrategy': '垃圾行分配策略',
    'teamBattle.focusDesc': '集中打擊 - 垃圾行發送給對方APM最高的玩家',
    'teamBattle.randomDesc': '隨機分配 - 垃圾行隨機發送給對方任意玩家',
    'teamBattle.evenDesc': '平均分配 - 垃圾行平均分配給對方所有玩家',
    'teamBattle.unknownStrategy': '未知策略',
    'teamBattle.createSuccess': '團戰房間創建成功！房間碼: ',
    'teamBattle.joinSuccess': '成功加入團戰房間！',
    'teamBattle.noActiveRooms': '暫無活躍的團戰房間',
    'teamBattle.enter4DigitCode': '輸入4位房間碼',
    'teamBattle.setTeamAndStrategy': '設置團隊規模和垃圾行策略',
    'teamBattle.2v2': '2v2 (4人對戰)',
    'teamBattle.3v3': '3v3 (6人對戰)',
    'teamBattle.4v4': '4v4 (8人對戰)',
    'teamBattle.2v2v2v2': '2v2/3v3/4v4 團隊對戰',
    
    // Multiplayer
    'multiplayer.title': '多人遊戲',
    'multiplayer.1v1': '1v1 對戰',
    'multiplayer.1v1Desc': '經典一對一俄羅斯方塊對戰',
    'multiplayer.ranked': '排位賽',
    'multiplayer.rankedDesc': '參與排位匹配，提升段位',
    'multiplayer.customRoom': '自定義房間',
    'multiplayer.customRoomDesc': '創建或加入自定義對戰房間',
    'multiplayer.battleRoyale': '大逃殺模式',
    'multiplayer.battleRoyaleDesc': '多人混戰，最後一人獲勝',
    'multiplayer.botRoom': 'AI 機器人對戰',
    'multiplayer.botRoomDesc': '與不同難度的 AI 機器人對戰',
    'multiplayer.needLoginMulti': '需要登入才能進行多人遊戲',
    'multiplayer.quickLogin': '訪客快速登入',
    
    // Bot Room
    'bot.createRoom': '創建Bot房間',
    'bot.createRoomDesc': '創建一個專門的Bot房間，可以添加不同難度的AI機器人進行對戰練習',
    'bot.availableRooms': '可用的Bot房間',
    'bot.noRooms': '暫無可用的Bot房間',
    'bot.aboutRooms': '關於Bot房間',
    'bot.aboutDesc1': 'Bot房間是專門與AI機器人對戰的遊戲模式',
    'bot.aboutDesc2': '房間中的Bot顯示為紅色方塊，易於識別',
    'bot.aboutDesc3': '支持4種不同難度的Bot：簡單、中等、困難、專家',
    'bot.aboutDesc4': '可以同時與多個Bot和真實玩家一起遊戲',
    'bot.aboutDesc5': '適合練習技巧和挑戰更高難度',
    'bot.room': 'Bot房間',
    'bot.connected': '已連接',
    'bot.connecting': '連接中...',
    'bot.startGame': '開始遊戲',
    'bot.creator': '創建者',
    'bot.players': '玩家',
    
    // Game Mode Selector
    'mode.select': '選擇遊戲模式',
    'mode.backToMain': '返回主選單',
    'mode.target': '目標',
    'mode.timeLimit': '時限',
    'mode.unlimited': '無限制遊戲',
    'mode.startGame': '開始遊戲',
    'mode.timed': '限時',
    'mode.sprint': '衝刺',
    'mode.targetLines': '目標: {lines} 行',
    'mode.timeLimitFormat': '時限: {time}',
    'mode.clearLines': '目標: 清除 {lines} 行'
  },
  
  en: {
    // Game related
    'game.title': 'Tetris Gaming Platform',
    'game.play': 'Start Playing',
    'game.singlePlayer': 'Single Player',
    'game.multiPlayer': 'Multiplayer',
    'game.ranked': 'Ranked',
    'game.sprint40': '40 Lines Sprint',
    'game.ultra2min': '2 Minute Ultra',
    'game.endless': 'Endless Mode',
    'game.freeForAll': 'Free For All',
    'game.oneVsOne': '1v1 Battle',
    'game.customRoom': 'Custom Room',
    'game.description': 'Experience the purest Tetris competition',
    'game.singlePlayerDesc': 'Challenge your limits and break personal records',
    'game.multiPlayerDesc': 'Real-time battles with global players',
    'game.rankedDesc': 'Compete for the highest rank',
    'game.gameOver': 'Game Over',
    'game.newRecord': 'New Record!',
    'game.score': 'Score',
    'game.lines': 'Lines',
    'game.level': 'Level',
    'game.time': 'Time',
    'game.restart': 'Restart',
    'game.continue': 'Continue',
    
    // Auth related
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.guest': 'Guest Mode',
    'auth.username': 'Username',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fillEmailPassword': 'Please fill in email and password',
    'auth.fillUsername': 'Please fill in username',
    'auth.loginError': 'Login Error',
    'auth.invalidCredentials': 'Invalid email or password, please check and try again',
    'auth.verifyEmail': 'Please verify your email first, check activation link in your inbox',
    'auth.networkError': 'Network connection issue, please check and try again',
    'auth.rateLimited': 'Too many login attempts, please try again later',
    'auth.requestAborted': 'Request aborted, please retry',
    'auth.loginSuccess': 'Login successful!',
    'auth.registerSuccess': 'Registration successful! Please check email for verification link',
    'auth.userExists': 'User already exists',
    'auth.checkEmailLink': 'Please check email verification link',
    'auth.registerFailed': 'Registration failed, please retry',
    'auth.forgotPassword': 'Forgot password?',
    'auth.guestLogin': 'Guest Login',
    'auth.guestLoginFailed': 'Guest login failed',
    'auth.guestDescription': 'Quickly start playing as a guest',
    'auth.noAccount': "Don't have an account? Register now",
    'auth.hasAccount': 'Already have an account? Login now',
    'auth.processing': 'Processing...',
    'auth.loginDesc': 'Login to your account to start playing',
    'auth.registerDesc': 'Create a new account',
    'auth.enterUsername': 'Enter username',
    'auth.enterEmail': 'Enter email address',
    'auth.enterPassword': 'Enter password',
    'auth.guestSuccess': 'Guest login successful',
    'auth.guestRestricted': 'Guest users cannot participate in ranked matches and tournaments',
    
    // Settings related
    'settings.controls': 'Controls',
    'settings.keyboard': 'Keyboard Settings',
    'settings.game': 'Game Settings',
    'settings.shortcuts': 'Shortcuts',
    'settings.das': 'DAS Rate',
    'settings.arr': 'ARR Speed',
    'settings.sdf': 'SDF Speed',
    'settings.preview': 'Preset Layout',
    'settings.customKeys': 'Custom Keys',
    'settings.moveLeft': 'Move Left',
    'settings.moveRight': 'Move Right',
    'settings.softDrop': 'Soft Drop',
    'settings.hardDrop': 'Hard Drop',
    'settings.rotateClockwise': 'Rotate Clockwise',
    'settings.rotateCounterclockwise': 'Rotate Counterclockwise',
    'settings.rotate180': '180° Rotation',
    'settings.hold': 'Hold',
    'settings.pause': 'Pause',
    'settings.keyboardInstructions': 'Key Mapping Instructions',
    'settings.keyboardTip': 'Click on the key box and press the key you want to set',
    'settings.controlsDesc': 'Customize keys and game parameters',
    'settings.livePreview': 'Live Preview',
    'settings.testWithKeys': 'Use ← → keys to test handling',
    'settings.maxUndoSteps': 'Max Undo Steps',
    
    // Room related
    'room.create': 'Create Room',
    'room.join': 'Join Room',
    'room.share': 'Share Room',
    'room.maxPlayers': 'Max Players',
    'room.needLogin': 'Login required to create room',
    'room.createFailed': 'Failed to create room, please retry',
    'room.createSuccess': 'Room created! Room code: ',
    'room.joinFailed': 'Failed to join room, please check room code',
    'room.joinSuccess': 'Successfully joined room',
    'room.enterCode': 'Please enter room code',
    'room.roomFull': 'Room is full or does not exist',
    'room.alreadyInRoom': 'You are already in this room',
    'room.activeRooms': 'Active Rooms',
    'room.onlinePlayers': 'Online Players',
    'room.quickJoin': 'Quick Join Room',
    'room.enterRoomCode': 'Enter 4-digit room code',
    'room.joining': 'Joining...',
    'room.notExist': 'Room does not exist or is closed',
    'room.noActiveRooms': 'No active rooms',
    'room.roomUnavailable': 'Room unavailable',
    
    // Replay related
    'replay.view': 'View Replay',
    'replay.speed': 'Replay Speed',
    'replay.title': 'Replay System',
    'replay.description': 'Watch and analyze game recordings',
    
    // Navigation
    'nav.home': 'Home',
    'nav.play': 'Play',
    'nav.multiplayer': 'Multiplayer',
    'nav.profile': 'Profile',
    'nav.leaderboard': 'Leaderboard',
    'nav.settings': 'Settings',
    'nav.backToMenu': 'Back to Menu',
    
    // Ranking
    'rank.system': 'Ranking System',
    'rank.current': 'Current Rank',
    'rank.points': 'Points',
    'rank.nextRank': 'Next Rank',
    'rank.promotion': 'Points needed for promotion',
    
    // Ads
    'ad.placeholder': 'Advertisement Space Available',
    'ad.contact': 'Contact Admin',
    
    // Income
    'income.donations': 'Donation Income',
    'income.ads': 'Ad Revenue',
    'income.total': 'Total Income',
    
    // Admin
    'admin.panel': 'Admin Panel',
    'admin.income': 'Income System',
    'admin.title': 'Admin Panel',
    'admin.description': 'Advertising and revenue management',
    'admin.adManagement': 'Ad Management System',
    'admin.createAd': 'Create Ad',
    'admin.editAd': 'Edit Ad',
    'admin.adTitle': 'Ad Title',
    'admin.adContent': 'Ad Content',
    'admin.adImage': 'Ad Image',
    'admin.adPosition': 'Ad Position',
    'admin.position.left': 'Left',
    'admin.position.right': 'Right',
    'admin.position.top': 'Top',
    'admin.position.bottom': 'Bottom',
    'admin.position.popup': 'Popup',
    'admin.priority': 'Priority',
    'admin.targetRegion': 'Target Region',
    'admin.targetLanguage': 'Target Language',
    'admin.startDate': 'Start Date',
    'admin.endDate': 'End Date',
    'admin.budget': 'Budget',
    'admin.frequencyCap': 'Frequency Cap',
    'admin.targetUrl': 'Click URL',
    'admin.abTestGroup': 'A/B Test Group',
    'admin.enableNow': 'Enable Now',
    'admin.cancel': 'Cancel',
    'admin.update': 'Update',
    'admin.create': 'Create',
    'admin.adList': 'Ad List',
    'admin.analytics': 'Analytics',
    'admin.operationLogs': 'Operation Logs',
    'admin.allAds': 'All Ads',
    'admin.status': 'Status',
    'admin.impressionsClicks': 'Impressions/Clicks',
    'admin.budgetSpent': 'Budget/Spent',
    'admin.actions': 'Actions',
    'admin.active': 'Active',
    'admin.disabled': 'Disabled',
    'admin.loadFailed': 'Failed to load ads',
    'admin.saveFailed': 'Failed to save ad',
    'admin.updateSuccess': 'Ad updated successfully',
    'admin.createSuccess': 'Ad created successfully',
    'admin.enableSuccess': 'Ad enabled',
    'admin.disableSuccess': 'Ad disabled',
    'admin.deleteConfirm': 'Are you sure you want to delete this ad?',
    'admin.deleteSuccess': 'Ad deleted successfully',
    'admin.deleteFailed': 'Delete failed',
    'admin.noPermission': 'No permission',
    'admin.noAccess': 'No access permission',
    'admin.loading': 'Loading...',
    
    // Common
    'common.welcome': 'Welcome back',
    'common.guestMode': 'Guest Mode',
    'common.needLogin': 'Login Required',
    'common.startMatch': 'Start Match',
    'common.startRank': 'Start Ranked',
    'common.backToHome': 'Back to Home',
    'common.openSettings': 'Open Game Settings',
    'common.enter': 'Enter',
    'common.back': 'Back',
    'common.copyright': 'Based on modern Tetris rules',
    'common.confirm': 'Confirm',
    'common.delete': 'Delete',
    'common.save': 'Save',
    'common.close': 'Close',
    'common.success': 'Success',
    'common.failed': 'Failed',
    'common.retry': 'Retry',
    'common.creating': 'Creating...',
    'common.loading': 'Loading...',
    'common.comingSoon': 'Coming Soon',
    'common.registeredUser': 'Registered User',
    'common.guestUser': 'Guest User',
    'common.loadStatsFailed': 'Failed to load stats',
    'common.networkError': 'Network connection error',
    'common.modeFailed': 'Mode selection failed, please retry',
    
    // Tutorial
    'tutorial.title': 'Game Tutorial',
    'tutorial.description': 'Learn advanced techniques and strategies',
    
    // Team Battle
    'teamBattle.title': 'Team Battle',
    'teamBattle.entryDesc': '2v2/3v3/4v4 team battles with three garbage strategies',
    'teamBattle.createRoom': 'Create Team Room',
    'teamBattle.joinRoom': 'Join Room',
    'teamBattle.activeRooms': 'Active Rooms',
    'teamBattle.strategy.focus': 'Focus Attack',
    'teamBattle.strategy.random': 'Random',
    'teamBattle.strategy.even': 'Even',
    'teamBattle.tabHint': 'Press Tab in match to switch garbage strategy',
    'teamBattle.teamSize': 'Team Size',
    'teamBattle.garbageStrategy': 'Garbage Distribution Strategy',
    'teamBattle.focusDesc': 'Focus Attack - Send garbage to opponent with highest APM',
    'teamBattle.randomDesc': 'Random - Send garbage randomly to any opponent',
    'teamBattle.evenDesc': 'Even - Distribute garbage evenly among all opponents',
    'teamBattle.unknownStrategy': 'Unknown strategy',
    'teamBattle.createSuccess': 'Team room created! Room code: ',
    'teamBattle.joinSuccess': 'Successfully joined team room!',
    'teamBattle.noActiveRooms': 'No active team rooms',
    'teamBattle.enter4DigitCode': 'Enter 4-digit room code',
    'teamBattle.setTeamAndStrategy': 'Set team size and garbage strategy',
    'teamBattle.2v2': '2v2 (4 players)',
    'teamBattle.3v3': '3v3 (6 players)',
    'teamBattle.4v4': '4v4 (8 players)',
    'teamBattle.2v2v2v2': '2v2/3v3/4v4 Team Battles',
    
    // Multiplayer
    'multiplayer.title': 'Multiplayer',
    'multiplayer.1v1': '1v1 Battle',
    'multiplayer.1v1Desc': 'Classic one-on-one Tetris battle',
    'multiplayer.ranked': 'Ranked',
    'multiplayer.rankedDesc': 'Participate in ranked matches, climb the ranks',
    'multiplayer.customRoom': 'Custom Room',
    'multiplayer.customRoomDesc': 'Create or join custom battle rooms',
    'multiplayer.battleRoyale': 'Battle Royale',
    'multiplayer.battleRoyaleDesc': 'Multi-player battle, last one standing wins',
    'multiplayer.botRoom': 'AI Bot Battle',
    'multiplayer.botRoomDesc': 'Battle against AI bots of varying difficulty',
    'multiplayer.needLoginMulti': 'Login required for multiplayer',
    'multiplayer.quickLogin': 'Quick Guest Login',
    
    // Bot Room
    'bot.createRoom': 'Create Bot Room',
    'bot.createRoomDesc': 'Create a dedicated bot room, add AI bots of different difficulties for practice',
    'bot.availableRooms': 'Available Bot Rooms',
    'bot.noRooms': 'No bot rooms available',
    'bot.aboutRooms': 'About Bot Rooms',
    'bot.aboutDesc1': 'Bot rooms are game modes for playing against AI bots',
    'bot.aboutDesc2': 'Bots in the room are displayed as red blocks for easy identification',
    'bot.aboutDesc3': 'Supports 4 difficulty levels: Easy, Medium, Hard, Expert',
    'bot.aboutDesc4': 'Can play with multiple bots and real players simultaneously',
    'bot.aboutDesc5': 'Great for practicing skills and challenging higher difficulties',
    'bot.room': 'Bot Room',
    'bot.connected': 'Connected',
    'bot.connecting': 'Connecting...',
    'bot.startGame': 'Start Game',
    'bot.creator': 'Creator',
    'bot.players': 'Players',
    
    // Game Mode Selector
    'mode.select': 'Select Game Mode',
    'mode.backToMain': 'Back to Main Menu',
    'mode.target': 'Target',
    'mode.timeLimit': 'Time Limit',
    'mode.unlimited': 'Unlimited Game',
    'mode.startGame': 'Start Game',
    'mode.timed': 'Timed',
    'mode.sprint': 'Sprint',
    'mode.targetLines': 'Target: {lines} lines',
    'mode.timeLimitFormat': 'Time: {time}',
    'mode.clearLines': 'Target: Clear {lines} lines'
  },
  
  ja: {
    // Game related
    'game.title': 'テトリスゲーミングプラットフォーム',
    'game.play': 'ゲーム開始',
    'game.singlePlayer': 'シングルプレイ',
    'game.multiPlayer': 'マルチプレイ',
    'game.ranked': 'ランクマッチ',
    'game.sprint40': '40ライン',
    'game.ultra2min': '2分間ウルトラ',
    'game.endless': 'エンドレス',
    'game.freeForAll': 'フリーフォーオール',
    'game.oneVsOne': '1対1バトル',
    'game.customRoom': 'カスタムルーム',
    'game.description': '最も純粋なテトリス競技を体験',
    'game.singlePlayerDesc': '自分の限界に挑戦し、個人記録を更新',
    'game.multiPlayerDesc': '世界中のプレイヤーとリアルタイムバトル',
    'game.rankedDesc': '最高ランクを目指して競争',
    'game.gameOver': 'ゲームオーバー',
    'game.newRecord': '新記録！',
    'game.score': 'スコア',
    'game.lines': 'ライン',
    'game.level': 'レベル',
    'game.time': '時間',
    'game.restart': 'リスタート',
    'game.continue': '続ける',
    
    // Auth related
    'auth.login': 'ログイン',
    'auth.register': '登録',
    'auth.guest': 'ゲストモード',
    'auth.username': 'ユーザー名',
    'auth.email': 'メール',
    'auth.password': 'パスワード',
    'auth.fillEmailPassword': 'メールとパスワードを入力してください',
    'auth.fillUsername': 'ユーザー名を入力してください',
    'auth.loginError': 'ログインエラー',
    'auth.invalidCredentials': 'メールまたはパスワードが間違っています',
    'auth.verifyEmail': 'メールを確認してください。受信トレイの確認リンクをクリックしてください',
    'auth.networkError': 'ネットワーク接続の問題があります。確認して再試行してください',
    'auth.rateLimited': 'ログイン試行が多すぎます。後で再試行してください',
    'auth.requestAborted': 'リクエストが中断されました。再試行してください',
    'auth.loginSuccess': 'ログイン成功！',
    'auth.registerSuccess': '登録成功！確認リンクのメールを確認してください',
    'auth.userExists': 'ユーザーは既に存在します',
    'auth.checkEmailLink': 'メール確認リンクを確認してください',
    'auth.registerFailed': '登録に失敗しました。再試行してください',
    'auth.forgotPassword': 'パスワードを忘れましたか？',
    'auth.guestLogin': 'ゲストログイン',
    'auth.guestLoginFailed': 'ゲストログインに失敗しました',
    'auth.guestDescription': 'ゲストとしてすぐにプレイ開始',
    'auth.noAccount': 'アカウントをお持ちでないですか？今すぐ登録',
    'auth.hasAccount': 'すでにアカウントをお持ちですか？ログイン',
    'auth.processing': '処理中...',
    'auth.loginDesc': 'アカウントにログインしてプレイを開始',
    'auth.registerDesc': '新しいアカウントを作成',
    'auth.enterUsername': 'ユーザー名を入力',
    'auth.enterEmail': 'メールアドレスを入力',
    'auth.enterPassword': 'パスワードを入力',
    'auth.guestSuccess': 'ゲストログイン成功',
    'auth.guestRestricted': 'ゲストユーザーはランクマッチとトーナメントに参加できません',
    
    // Settings related
    'settings.controls': 'コントロール',
    'settings.keyboard': 'キーボード設定',
    'settings.game': 'ゲーム設定',
    'settings.shortcuts': 'ショートカット',
    'settings.das': 'DAS速度',
    'settings.arr': 'ARR速度',
    'settings.sdf': 'SDF速度',
    'settings.preview': 'プリセットレイアウト',
    'settings.customKeys': 'カスタムキー',
    'settings.moveLeft': '左移動',
    'settings.moveRight': '右移動',
    'settings.softDrop': 'ソフトドロップ',
    'settings.hardDrop': 'ハードドロップ',
    'settings.rotateClockwise': '時計回り回転',
    'settings.rotateCounterclockwise': '反時計回り回転',
    'settings.rotate180': '180度回転',
    'settings.hold': 'ホールド',
    'settings.pause': '一時停止',
    'settings.keyboardInstructions': 'キーマッピング説明',
    'settings.keyboardTip': 'キーボックスをクリックして設定したいキーを押してください',
    'settings.controlsDesc': 'キーとゲームパラメータをカスタマイズ',
    'settings.livePreview': 'ライブプレビュー',
    'settings.testWithKeys': '← → キーでハンドリングをテスト',
    'settings.maxUndoSteps': '最大アンドゥステップ',
    
    // Room related
    'room.create': 'ルーム作成',
    'room.join': 'ルーム参加',
    'room.share': 'ルーム共有',
    'room.maxPlayers': '最大プレイヤー数',
    'room.needLogin': 'ルーム作成にはログインが必要です',
    'room.createFailed': 'ルーム作成に失敗しました。再試行してください',
    'room.createSuccess': 'ルーム作成成功！ルームコード: ',
    'room.joinFailed': 'ルーム参加に失敗しました。ルームコードを確認してください',
    'room.joinSuccess': 'ルームに参加しました',
    'room.enterCode': 'ルームコードを入力してください',
    'room.roomFull': 'ルームが満員または存在しません',
    'room.alreadyInRoom': 'すでにこのルームにいます',
    'room.activeRooms': 'アクティブルーム',
    'room.onlinePlayers': 'オンラインプレイヤー',
    'room.quickJoin': 'クイックルーム参加',
    'room.enterRoomCode': '4桁のルームコードを入力',
    'room.joining': '参加中...',
    'room.notExist': 'ルームが存在しないか、閉じています',
    'room.noActiveRooms': 'アクティブなルームがありません',
    'room.roomUnavailable': 'ルームは利用できません',
    
    // Replay related
    'replay.view': 'リプレイ表示',
    'replay.speed': 'リプレイ速度',
    'replay.title': 'リプレイシステム',
    'replay.description': 'ゲーム録画を見て分析する',
    
    // Navigation
    'nav.home': 'ホーム',
    'nav.play': 'プレイ',
    'nav.multiplayer': 'マルチプレイ',
    'nav.profile': 'プロフィール',
    'nav.leaderboard': 'リーダーボード',
    'nav.settings': '設定',
    'nav.backToMenu': 'メニューに戻る',
    
    // Ranking
    'rank.system': 'ランキングシステム',
    'rank.current': '現在のランク',
    'rank.points': 'ポイント',
    'rank.nextRank': '次のランク',
    'rank.promotion': '昇格に必要なポイント',
    
    // Ads
    'ad.placeholder': '広告スペース利用可能',
    'ad.contact': '管理者に連絡',
    
    // Income
    'income.donations': '寄付収入',
    'income.ads': '広告収入',
    'income.total': '総収入',
    
    // Admin
    'admin.panel': '管理パネル',
    'admin.income': '収入システム',
    'admin.title': '管理パネル',
    'admin.description': '広告と収入管理',
    'admin.adManagement': '広告管理システム',
    'admin.createAd': '広告作成',
    'admin.editAd': '広告編集',
    'admin.adTitle': '広告タイトル',
    'admin.adContent': '広告内容',
    'admin.adImage': '広告画像',
    'admin.adPosition': '広告位置',
    'admin.position.left': '左',
    'admin.position.right': '右',
    'admin.position.top': '上',
    'admin.position.bottom': '下',
    'admin.position.popup': 'ポップアップ',
    'admin.priority': '優先度',
    'admin.targetRegion': 'ターゲット地域',
    'admin.targetLanguage': 'ターゲット言語',
    'admin.startDate': '開始日',
    'admin.endDate': '終了日',
    'admin.budget': '予算',
    'admin.frequencyCap': '表示頻度上限',
    'admin.targetUrl': 'クリックURL',
    'admin.abTestGroup': 'A/Bテストグループ',
    'admin.enableNow': '今すぐ有効化',
    'admin.cancel': 'キャンセル',
    'admin.update': '更新',
    'admin.create': '作成',
    'admin.adList': '広告リスト',
    'admin.analytics': '分析',
    'admin.operationLogs': '操作ログ',
    'admin.allAds': 'すべての広告',
    'admin.status': 'ステータス',
    'admin.impressionsClicks': 'インプレッション/クリック',
    'admin.budgetSpent': '予算/消費',
    'admin.actions': 'アクション',
    'admin.active': 'アクティブ',
    'admin.disabled': '無効',
    'admin.loadFailed': '広告の読み込みに失敗しました',
    'admin.saveFailed': '広告の保存に失敗しました',
    'admin.updateSuccess': '広告が更新されました',
    'admin.createSuccess': '広告が作成されました',
    'admin.enableSuccess': '広告が有効になりました',
    'admin.disableSuccess': '広告が無効になりました',
    'admin.deleteConfirm': 'この広告を削除しますか？',
    'admin.deleteSuccess': '広告が削除されました',
    'admin.deleteFailed': '削除に失敗しました',
    'admin.noPermission': '権限がありません',
    'admin.noAccess': 'アクセス権限がありません',
    'admin.loading': '読み込み中...',
    
    // Common
    'common.welcome': 'おかえりなさい',
    'common.guestMode': 'ゲストモード',
    'common.needLogin': 'ログインが必要',
    'common.startMatch': 'マッチ開始',
    'common.startRank': 'ランク開始',
    'common.backToHome': 'ホームに戻る',
    'common.openSettings': 'ゲーム設定を開く',
    'common.enter': '入る',
    'common.back': '戻る',
    'common.copyright': '現代テトリスルールに基づく',
    'common.confirm': '確認',
    'common.delete': '削除',
    'common.save': '保存',
    'common.close': '閉じる',
    'common.success': '成功',
    'common.failed': '失敗',
    'common.retry': '再試行',
    'common.creating': '作成中...',
    'common.loading': '読み込み中...',
    'common.comingSoon': '近日公開',
    'common.registeredUser': '登録ユーザー',
    'common.guestUser': 'ゲストユーザー',
    'common.loadStatsFailed': '統計の読み込みに失敗',
    'common.networkError': 'ネットワーク接続エラー',
    'common.modeFailed': 'モード選択に失敗しました。再試行してください',
    
    // Tutorial
    'tutorial.title': 'ゲームチュートリアル',
    'tutorial.description': '高度なテクニックと戦略を学ぶ',
    
    // Team Battle
    'teamBattle.title': '団体戦',
    'teamBattle.entryDesc': '2v2/3v3/4v4 チーム戦、3つの攻撃戦略',
    'teamBattle.createRoom': 'ルーム作成',
    'teamBattle.joinRoom': 'ルーム参加',
    'teamBattle.activeRooms': 'アクティブルーム',
    'teamBattle.strategy.focus': '集中攻撃',
    'teamBattle.strategy.random': 'ランダム',
    'teamBattle.strategy.even': '均等配分',
    'teamBattle.tabHint': '試合中にTabで攻撃配分を切替',
    'teamBattle.teamSize': 'チームサイズ',
    'teamBattle.garbageStrategy': 'ガベージ配分戦略',
    'teamBattle.focusDesc': '集中攻撃 - APM最高の相手にガベージを送る',
    'teamBattle.randomDesc': 'ランダム - ランダムな相手にガベージを送る',
    'teamBattle.evenDesc': '均等配分 - すべての相手に均等にガベージを配分',
    'teamBattle.unknownStrategy': '不明な戦略',
    'teamBattle.createSuccess': 'チームルーム作成成功！ルームコード: ',
    'teamBattle.joinSuccess': 'チームルームに参加しました！',
    'teamBattle.noActiveRooms': 'アクティブなチームルームがありません',
    'teamBattle.enter4DigitCode': '4桁のルームコードを入力',
    'teamBattle.setTeamAndStrategy': 'チームサイズとガベージ戦略を設定',
    'teamBattle.2v2': '2v2 (4プレイヤー)',
    'teamBattle.3v3': '3v3 (6プレイヤー)',
    'teamBattle.4v4': '4v4 (8プレイヤー)',
    'teamBattle.2v2v2v2': '2v2/3v3/4v4 チーム戦',
    
    // Multiplayer
    'multiplayer.title': 'マルチプレイ',
    'multiplayer.1v1': '1対1バトル',
    'multiplayer.1v1Desc': 'クラシック1対1テトリスバトル',
    'multiplayer.ranked': 'ランクマッチ',
    'multiplayer.rankedDesc': 'ランクマッチに参加してランクを上げる',
    'multiplayer.customRoom': 'カスタムルーム',
    'multiplayer.customRoomDesc': 'カスタムバトルルームを作成または参加',
    'multiplayer.battleRoyale': 'バトルロイヤル',
    'multiplayer.battleRoyaleDesc': '複数プレイヤーバトル、最後に残った者が勝利',
    'multiplayer.botRoom': 'AIボットバトル',
    'multiplayer.botRoomDesc': '様々な難易度のAIボットと対戦',
    'multiplayer.needLoginMulti': 'マルチプレイにはログインが必要です',
    'multiplayer.quickLogin': 'クイックゲストログイン',
    
    // Bot Room
    'bot.createRoom': 'Botルーム作成',
    'bot.createRoomDesc': '専用のBotルームを作成し、異なる難易度のAIボットを追加して練習',
    'bot.availableRooms': '利用可能なBotルーム',
    'bot.noRooms': '利用可能なBotルームがありません',
    'bot.aboutRooms': 'Botルームについて',
    'bot.aboutDesc1': 'BotルームはAIボットと対戦するゲームモードです',
    'bot.aboutDesc2': 'ルーム内のボットは赤いブロックで表示され、識別しやすい',
    'bot.aboutDesc3': '4つの難易度レベルをサポート：簡単、中、難しい、エキスパート',
    'bot.aboutDesc4': '複数のボットと実際のプレイヤーと同時にプレイ可能',
    'bot.aboutDesc5': 'スキル練習や高難度への挑戦に最適',
    'bot.room': 'Botルーム',
    'bot.connected': '接続済み',
    'bot.connecting': '接続中...',
    'bot.startGame': 'ゲーム開始',
    'bot.creator': '作成者',
    'bot.players': 'プレイヤー',
    
    // Game Mode Selector
    'mode.select': 'ゲームモードを選択',
    'mode.backToMain': 'メインメニューに戻る',
    'mode.target': '目標',
    'mode.timeLimit': '制限時間',
    'mode.unlimited': '無制限ゲーム',
    'mode.startGame': 'ゲーム開始',
    'mode.timed': '時間制限',
    'mode.sprint': 'スプリント',
    'mode.targetLines': '目標: {lines} ライン',
    'mode.timeLimitFormat': '制限時間: {time}',
    'mode.clearLines': '目標: {lines} ラインクリア'
  },
  
  ko: {
    // Game related
    'game.title': '테트리스 게이밍 플랫폼',
    'game.play': '게임 시작',
    'game.singlePlayer': '싱글 플레이어',
    'game.multiPlayer': '멀티 플레이어',
    'game.ranked': '랭크전',
    'game.sprint40': '40라인 스프린트',
    'game.ultra2min': '2분 울트라',
    'game.endless': '무한 모드',
    'game.freeForAll': '자유 대전',
    'game.oneVsOne': '1대1 배틀',
    'game.customRoom': '커스텀 룸',
    'game.description': '가장 순수한 테트리스 경쟁 경험',
    'game.singlePlayerDesc': '자신의 한계에 도전하고 개인 기록 갱신',
    'game.multiPlayerDesc': '전 세계 플레이어와 실시간 배틀',
    'game.rankedDesc': '최고 랭크를 위한 경쟁',
    'game.gameOver': '게임 오버',
    'game.newRecord': '새 기록!',
    'game.score': '점수',
    'game.lines': '라인',
    'game.level': '레벨',
    'game.time': '시간',
    'game.restart': '다시 시작',
    'game.continue': '계속',
    
    // Auth related
    'auth.login': '로그인',
    'auth.register': '회원가입',
    'auth.guest': '게스트 모드',
    'auth.username': '사용자명',
    'auth.email': '이메일',
    'auth.password': '비밀번호',
    'auth.fillEmailPassword': '이메일과 비밀번호를 입력해주세요',
    'auth.fillUsername': '사용자명을 입력해주세요',
    'auth.loginError': '로그인 오류',
    'auth.invalidCredentials': '이메일 또는 비밀번호가 잘못되었습니다',
    'auth.verifyEmail': '먼저 이메일을 인증해주세요. 받은 편지함의 인증 링크를 확인하세요',
    'auth.networkError': '네트워크 연결 문제가 있습니다. 확인 후 다시 시도해주세요',
    'auth.rateLimited': '로그인 시도가 너무 많습니다. 나중에 다시 시도해주세요',
    'auth.requestAborted': '요청이 중단되었습니다. 다시 시도해주세요',
    'auth.loginSuccess': '로그인 성공!',
    'auth.registerSuccess': '회원가입 성공! 이메일의 인증 링크를 확인해주세요',
    'auth.userExists': '사용자가 이미 존재합니다',
    'auth.checkEmailLink': '이메일 인증 링크를 확인해주세요',
    'auth.registerFailed': '회원가입에 실패했습니다. 다시 시도해주세요',
    'auth.forgotPassword': '비밀번호를 잊으셨나요?',
    'auth.guestLogin': '게스트 로그인',
    'auth.guestLoginFailed': '게스트 로그인에 실패했습니다',
    'auth.guestDescription': '게스트로 빠르게 플레이 시작',
    'auth.noAccount': '계정이 없으신가요? 지금 가입하세요',
    'auth.hasAccount': '이미 계정이 있으신가요? 로그인',
    'auth.processing': '처리 중...',
    'auth.loginDesc': '계정에 로그인하여 플레이 시작',
    'auth.registerDesc': '새 계정 만들기',
    'auth.enterUsername': '사용자명 입력',
    'auth.enterEmail': '이메일 주소 입력',
    'auth.enterPassword': '비밀번호 입력',
    'auth.guestSuccess': '게스트 로그인 성공',
    'auth.guestRestricted': '게스트 사용자는 랭크 매치와 토너먼트에 참여할 수 없습니다',
    
    // Settings related
    'settings.controls': '컨트롤',
    'settings.keyboard': '키보드 설정',
    'settings.game': '게임 설정',
    'settings.shortcuts': '바로가기',
    'settings.das': 'DAS 속도',
    'settings.arr': 'ARR 속도',
    'settings.sdf': 'SDF 속도',
    'settings.preview': '프리셋 레이아웃',
    'settings.customKeys': '커스텀 키',
    'settings.moveLeft': '왼쪽 이동',
    'settings.moveRight': '오른쪽 이동',
    'settings.softDrop': '소프트 드롭',
    'settings.hardDrop': '하드 드롭',
    'settings.rotateClockwise': '시계방향 회전',
    'settings.rotateCounterclockwise': '반시계방향 회전',
    'settings.rotate180': '180도 회전',
    'settings.hold': '홀드',
    'settings.pause': '일시정지',
    'settings.keyboardInstructions': '키 매핑 설명',
    'settings.keyboardTip': '키 박스를 클릭하고 설정하고 싶은 키를 누르세요',
    'settings.controlsDesc': '키와 게임 매개변수 커스터마이징',
    'settings.livePreview': '실시간 미리보기',
    'settings.testWithKeys': '← → 키로 핸들링 테스트',
    'settings.maxUndoSteps': '최대 실행 취소 단계',
    
    // Room related
    'room.create': '룸 생성',
    'room.join': '룸 참가',
    'room.share': '룸 공유',
    'room.maxPlayers': '최대 플레이어',
    'room.needLogin': '룸 생성에는 로그인이 필요합니다',
    'room.createFailed': '룸 생성에 실패했습니다. 다시 시도해주세요',
    'room.createSuccess': '룸 생성 성공! 룸 코드: ',
    'room.joinFailed': '룸 참가에 실패했습니다. 룸 코드를 확인해주세요',
    'room.joinSuccess': '룸에 참가했습니다',
    'room.enterCode': '룸 코드를 입력해주세요',
    'room.roomFull': '룸이 가득 찼거나 존재하지 않습니다',
    'room.alreadyInRoom': '이미 이 룸에 있습니다',
    'room.activeRooms': '활성 룸',
    'room.onlinePlayers': '온라인 플레이어',
    'room.quickJoin': '빠른 룸 참가',
    'room.enterRoomCode': '4자리 룸 코드 입력',
    'room.joining': '참가 중...',
    'room.notExist': '룸이 존재하지 않거나 닫혔습니다',
    'room.noActiveRooms': '활성 룸이 없습니다',
    'room.roomUnavailable': '룸을 사용할 수 없습니다',
    
    // Replay related
    'replay.view': '리플레이 보기',
    'replay.speed': '리플레이 속도',
    'replay.title': '리플레이 시스템',
    'replay.description': '게임 녹화 시청 및 분석',
    
    // Navigation
    'nav.home': '홈',
    'nav.play': '플레이',
    'nav.multiplayer': '멀티플레이어',
    'nav.profile': '프로필',
    'nav.leaderboard': '리더보드',
    'nav.settings': '설정',
    'nav.backToMenu': '메뉴로 돌아가기',
    
    // Ranking
    'rank.system': '랭킹 시스템',
    'rank.current': '현재 랭크',
    'rank.points': '포인트',
    'rank.nextRank': '다음 랭크',
    'rank.promotion': '승급 필요 포인트',
    
    // Ads
    'ad.placeholder': '광고 공간 사용 가능',
    'ad.contact': '관리자 연락',
    
    // Income
    'income.donations': '기부 수입',
    'income.ads': '광고 수입',
    'income.total': '총 수입',
    
    // Admin
    'admin.panel': '관리자 패널',
    'admin.income': '수입 시스템',
    'admin.title': '관리자 패널',
    'admin.description': '광고 및 수익 관리',
    'admin.adManagement': '광고 관리 시스템',
    'admin.createAd': '광고 생성',
    'admin.editAd': '광고 편집',
    'admin.adTitle': '광고 제목',
    'admin.adContent': '광고 내용',
    'admin.adImage': '광고 이미지',
    'admin.adPosition': '광고 위치',
    'admin.position.left': '왼쪽',
    'admin.position.right': '오른쪽',
    'admin.position.top': '위',
    'admin.position.bottom': '아래',
    'admin.position.popup': '팝업',
    'admin.priority': '우선순위',
    'admin.targetRegion': '대상 지역',
    'admin.targetLanguage': '대상 언어',
    'admin.startDate': '시작일',
    'admin.endDate': '종료일',
    'admin.budget': '예산',
    'admin.frequencyCap': '빈도 제한',
    'admin.targetUrl': '클릭 URL',
    'admin.abTestGroup': 'A/B 테스트 그룹',
    'admin.enableNow': '지금 활성화',
    'admin.cancel': '취소',
    'admin.update': '업데이트',
    'admin.create': '생성',
    'admin.adList': '광고 목록',
    'admin.analytics': '분석',
    'admin.operationLogs': '작업 로그',
    'admin.allAds': '모든 광고',
    'admin.status': '상태',
    'admin.impressionsClicks': '노출/클릭',
    'admin.budgetSpent': '예산/지출',
    'admin.actions': '작업',
    'admin.active': '활성',
    'admin.disabled': '비활성',
    'admin.loadFailed': '광고 로드 실패',
    'admin.saveFailed': '광고 저장 실패',
    'admin.updateSuccess': '광고가 업데이트되었습니다',
    'admin.createSuccess': '광고가 생성되었습니다',
    'admin.enableSuccess': '광고가 활성화되었습니다',
    'admin.disableSuccess': '광고가 비활성화되었습니다',
    'admin.deleteConfirm': '이 광고를 삭제하시겠습니까?',
    'admin.deleteSuccess': '광고가 삭제되었습니다',
    'admin.deleteFailed': '삭제 실패',
    'admin.noPermission': '권한 없음',
    'admin.noAccess': '접근 권한 없음',
    'admin.loading': '로딩 중...',
    
    // Common
    'common.welcome': '다시 오신 것을 환영합니다',
    'common.guestMode': '게스트 모드',
    'common.needLogin': '로그인 필요',
    'common.startMatch': '매치 시작',
    'common.startRank': '랭크 시작',
    'common.backToHome': '홈으로 돌아가기',
    'common.openSettings': '게임 설정 열기',
    'common.enter': '입력',
    'common.back': '뒤로',
    'common.copyright': '현대 테트리스 규칙 기반',
    'common.confirm': '확인',
    'common.delete': '삭제',
    'common.save': '저장',
    'common.close': '닫기',
    'common.success': '성공',
    'common.failed': '실패',
    'common.retry': '재시도',
    'common.creating': '생성 중...',
    'common.loading': '로딩 중...',
    'common.comingSoon': '곧 출시',
    'common.registeredUser': '등록 사용자',
    'common.guestUser': '게스트 사용자',
    'common.loadStatsFailed': '통계 로드 실패',
    'common.networkError': '네트워크 연결 오류',
    'common.modeFailed': '모드 선택 실패. 다시 시도해주세요',
    
    // Tutorial
    'tutorial.title': '게임 튜토리얼',
    'tutorial.description': '고급 기술과 전략 배우기',
    
    // Team Battle
    'teamBattle.title': '팀 배틀',
    'teamBattle.entryDesc': '2v2/3v3/4v4 팀 전투, 3가지 공격 전략',
    'teamBattle.createRoom': '팀 룸 생성',
    'teamBattle.joinRoom': '룸 참가',
    'teamBattle.activeRooms': '활성 룸',
    'teamBattle.strategy.focus': '집중 공격',
    'teamBattle.strategy.random': '랜덤',
    'teamBattle.strategy.even': '균등 배분',
    'teamBattle.tabHint': '경기 중 Tab으로 공격 전략 전환',
    'teamBattle.teamSize': '팀 사이즈',
    'teamBattle.garbageStrategy': '가비지 배분 전략',
    'teamBattle.focusDesc': '집중 공격 - APM 가장 높은 상대에게 가비지 전송',
    'teamBattle.randomDesc': '랜덤 - 무작위 상대에게 가비지 전송',
    'teamBattle.evenDesc': '균등 배분 - 모든 상대에게 균등하게 가비지 배분',
    'teamBattle.unknownStrategy': '알 수 없는 전략',
    'teamBattle.createSuccess': '팀 룸 생성 성공! 룸 코드: ',
    'teamBattle.joinSuccess': '팀 룸에 참가했습니다!',
    'teamBattle.noActiveRooms': '활성 팀 룸이 없습니다',
    'teamBattle.enter4DigitCode': '4자리 룸 코드 입력',
    'teamBattle.setTeamAndStrategy': '팀 사이즈와 가비지 전략 설정',
    'teamBattle.2v2': '2v2 (4명)',
    'teamBattle.3v3': '3v3 (6명)',
    'teamBattle.4v4': '4v4 (8명)',
    'teamBattle.2v2v2v2': '2v2/3v3/4v4 팀 전투',
    
    // Multiplayer
    'multiplayer.title': '멀티플레이어',
    'multiplayer.1v1': '1대1 배틀',
    'multiplayer.1v1Desc': '클래식 1대1 테트리스 배틀',
    'multiplayer.ranked': '랭크 매치',
    'multiplayer.rankedDesc': '랭크 매치에 참가하여 랭크 상승',
    'multiplayer.customRoom': '커스텀 룸',
    'multiplayer.customRoomDesc': '커스텀 배틀 룸 생성 또는 참가',
    'multiplayer.battleRoyale': '배틀 로얄',
    'multiplayer.battleRoyaleDesc': '다중 플레이어 배틀, 마지막 생존자 승리',
    'multiplayer.botRoom': 'AI 봇 배틀',
    'multiplayer.botRoomDesc': '다양한 난이도의 AI 봇과 대전',
    'multiplayer.needLoginMulti': '멀티플레이어는 로그인이 필요합니다',
    'multiplayer.quickLogin': '빠른 게스트 로그인',
    
    // Bot Room
    'bot.createRoom': '봇 룸 생성',
    'bot.createRoomDesc': '전용 봇 룸을 만들고 다양한 난이도의 AI 봇을 추가하여 연습',
    'bot.availableRooms': '사용 가능한 봇 룸',
    'bot.noRooms': '사용 가능한 봇 룸이 없습니다',
    'bot.aboutRooms': '봇 룸 정보',
    'bot.aboutDesc1': '봇 룸은 AI 봇과 대전하는 게임 모드입니다',
    'bot.aboutDesc2': '룸의 봇은 빨간색 블록으로 표시되어 쉽게 식별 가능',
    'bot.aboutDesc3': '4가지 난이도 지원: 쉬움, 보통, 어려움, 전문가',
    'bot.aboutDesc4': '여러 봇과 실제 플레이어와 동시에 플레이 가능',
    'bot.aboutDesc5': '스킬 연습과 고난이도 도전에 적합',
    'bot.room': '봇 룸',
    'bot.connected': '연결됨',
    'bot.connecting': '연결 중...',
    'bot.startGame': '게임 시작',
    'bot.creator': '생성자',
    'bot.players': '플레이어',
    
    // Game Mode Selector
    'mode.select': '게임 모드 선택',
    'mode.backToMain': '메인 메뉴로 돌아가기',
    'mode.target': '목표',
    'mode.timeLimit': '시간 제한',
    'mode.unlimited': '무제한 게임',
    'mode.startGame': '게임 시작',
    'mode.timed': '시간제한',
    'mode.sprint': '스프린트',
    'mode.targetLines': '목표: {lines} 라인',
    'mode.timeLimitFormat': '제한시간: {time}',
    'mode.clearLines': '목표: {lines} 라인 클리어'
  },
  
  es: {
    // Game related
    'game.title': 'Plataforma de Gaming Tetris',
    'game.play': 'Comenzar Juego',
    'game.singlePlayer': 'Un Jugador',
    'game.multiPlayer': 'Multijugador',
    'game.ranked': 'Clasificatorio',
    'game.sprint40': 'Sprint 40 Líneas',
    'game.ultra2min': 'Ultra 2 Minutos',
    'game.endless': 'Modo Infinito',
    'game.freeForAll': 'Todos contra Todos',
    'game.oneVsOne': 'Batalla 1v1',
    'game.customRoom': 'Sala Personalizada',
    'game.description': 'Experimenta la competición de Tetris más pura',
    'game.singlePlayerDesc': 'Desafía tus límites y rompe récords personales',
    'game.multiPlayerDesc': 'Batallas en tiempo real con jugadores globales',
    'game.rankedDesc': 'Compite por el rango más alto',
    'game.gameOver': 'Fin del Juego',
    'game.newRecord': '¡Nuevo Récord!',
    'game.score': 'Puntuación',
    'game.lines': 'Líneas',
    'game.level': 'Nivel',
    'game.time': 'Tiempo',
    'game.restart': 'Reiniciar',
    'game.continue': 'Continuar',
    
    // Auth related
    'auth.login': 'Iniciar Sesión',
    'auth.register': 'Registrarse',
    'auth.guest': 'Modo Invitado',
    'auth.username': 'Nombre de Usuario',
    'auth.email': 'Correo Electrónico',
    'auth.password': 'Contraseña',
    'auth.fillEmailPassword': 'Por favor ingrese correo y contraseña',
    'auth.fillUsername': 'Por favor ingrese nombre de usuario',
    'auth.loginError': 'Error de inicio de sesión',
    'auth.invalidCredentials': 'Correo o contraseña inválidos, verifique e intente de nuevo',
    'auth.verifyEmail': 'Por favor verifique su correo primero, revise el enlace de activación',
    'auth.networkError': 'Problema de conexión de red, verifique e intente de nuevo',
    'auth.rateLimited': 'Demasiados intentos de inicio de sesión, intente más tarde',
    'auth.requestAborted': 'Solicitud cancelada, por favor reintente',
    'auth.loginSuccess': '¡Inicio de sesión exitoso!',
    'auth.registerSuccess': '¡Registro exitoso! Revise el enlace de verificación en su correo',
    'auth.userExists': 'El usuario ya existe',
    'auth.checkEmailLink': 'Por favor revise el enlace de verificación de correo',
    'auth.registerFailed': 'Registro fallido, intente de nuevo',
    'auth.forgotPassword': '¿Olvidó su contraseña?',
    'auth.guestLogin': 'Inicio como Invitado',
    'auth.guestLoginFailed': 'Error al iniciar como invitado',
    'auth.guestDescription': 'Comience a jugar rápidamente como invitado',
    'auth.noAccount': '¿No tiene cuenta? Regístrese ahora',
    'auth.hasAccount': '¿Ya tiene cuenta? Inicie sesión',
    'auth.processing': 'Procesando...',
    'auth.loginDesc': 'Inicie sesión en su cuenta para comenzar a jugar',
    'auth.registerDesc': 'Crear una cuenta nueva',
    'auth.enterUsername': 'Ingrese nombre de usuario',
    'auth.enterEmail': 'Ingrese dirección de correo',
    'auth.enterPassword': 'Ingrese contraseña',
    'auth.guestSuccess': 'Inicio de invitado exitoso',
    'auth.guestRestricted': 'Los invitados no pueden participar en partidas clasificatorias y torneos',
    
    // Settings related
    'settings.controls': 'Controles',
    'settings.keyboard': 'Configuración de Teclado',
    'settings.game': 'Configuración de Juego',
    'settings.shortcuts': 'Atajos',
    'settings.das': 'Velocidad DAS',
    'settings.arr': 'Velocidad ARR',
    'settings.sdf': 'Velocidad SDF',
    'settings.preview': 'Diseño Preestablecido',
    'settings.customKeys': 'Teclas Personalizadas',
    'settings.moveLeft': 'Mover Izquierda',
    'settings.moveRight': 'Mover Derecha',
    'settings.softDrop': 'Caída Suave',
    'settings.hardDrop': 'Caída Dura',
    'settings.rotateClockwise': 'Rotar Horario',
    'settings.rotateCounterclockwise': 'Rotar Antihorario',
    'settings.rotate180': 'Rotación 180°',
    'settings.hold': 'Retener',
    'settings.pause': 'Pausa',
    'settings.keyboardInstructions': 'Instrucciones de Mapeo de Teclas',
    'settings.keyboardTip': 'Haz clic en la caja de tecla y presiona la tecla que quieres configurar',
    'settings.controlsDesc': 'Personalizar teclas y parámetros de juego',
    'settings.livePreview': 'Vista Previa en Vivo',
    'settings.testWithKeys': 'Usar teclas ← → para probar el manejo',
    'settings.maxUndoSteps': 'Pasos de Deshacer Máximo',
    
    // Room related
    'room.create': 'Crear Sala',
    'room.join': 'Unirse a Sala',
    'room.share': 'Compartir Sala',
    'room.maxPlayers': 'Máximo de Jugadores',
    'room.needLogin': 'Se requiere iniciar sesión para crear sala',
    'room.createFailed': 'Error al crear sala, intente de nuevo',
    'room.createSuccess': '¡Sala creada! Código: ',
    'room.joinFailed': 'Error al unirse a la sala, verifique el código',
    'room.joinSuccess': 'Se unió exitosamente a la sala',
    'room.enterCode': 'Por favor ingrese el código de sala',
    'room.roomFull': 'La sala está llena o no existe',
    'room.alreadyInRoom': 'Ya está en esta sala',
    'room.activeRooms': 'Salas Activas',
    'room.onlinePlayers': 'Jugadores en Línea',
    'room.quickJoin': 'Unirse Rápido a Sala',
    'room.enterRoomCode': 'Ingrese código de 4 dígitos',
    'room.joining': 'Uniéndose...',
    'room.notExist': 'La sala no existe o está cerrada',
    'room.noActiveRooms': 'No hay salas activas',
    'room.roomUnavailable': 'Sala no disponible',
    
    // Replay related
    'replay.view': 'Ver Repetición',
    'replay.speed': 'Velocidad de Repetición',
    'replay.title': 'Sistema de Repetición',
    'replay.description': 'Ver y analizar grabaciones de juego',
    
    // Navigation
    'nav.home': 'Inicio',
    'nav.play': 'Jugar',
    'nav.multiplayer': 'Multijugador',
    'nav.profile': 'Perfil',
    'nav.leaderboard': 'Tabla de Líderes',
    'nav.settings': 'Configuración',
    'nav.backToMenu': 'Volver al Menú',
    
    // Ranking
    'rank.system': 'Sistema de Clasificación',
    'rank.current': 'Rango Actual',
    'rank.points': 'Puntos',
    'rank.nextRank': 'Siguiente Rango',
    'rank.promotion': 'Puntos necesarios para promoción',
    
    // Ads
    'ad.placeholder': 'Espacio Publicitario Disponible',
    'ad.contact': 'Contactar Administrador',
    
    // Income
    'income.donations': 'Ingresos por Donaciones',
    'income.ads': 'Ingresos por Publicidad',
    'income.total': 'Ingresos Totales',
    
    // Admin
    'admin.panel': 'Panel de Administración',
    'admin.income': 'Sistema de Ingresos',
    'admin.title': 'Panel de Administración',
    'admin.description': 'Gestión de publicidad e ingresos',
    'admin.adManagement': 'Sistema de Gestión de Anuncios',
    'admin.createAd': 'Crear Anuncio',
    'admin.editAd': 'Editar Anuncio',
    'admin.adTitle': 'Título del Anuncio',
    'admin.adContent': 'Contenido del Anuncio',
    'admin.adImage': 'Imagen del Anuncio',
    'admin.adPosition': 'Posición del Anuncio',
    'admin.position.left': 'Izquierda',
    'admin.position.right': 'Derecha',
    'admin.position.top': 'Arriba',
    'admin.position.bottom': 'Abajo',
    'admin.position.popup': 'Emergente',
    'admin.priority': 'Prioridad',
    'admin.targetRegion': 'Región Objetivo',
    'admin.targetLanguage': 'Idioma Objetivo',
    'admin.startDate': 'Fecha de Inicio',
    'admin.endDate': 'Fecha de Fin',
    'admin.budget': 'Presupuesto',
    'admin.frequencyCap': 'Límite de Frecuencia',
    'admin.targetUrl': 'URL de Clic',
    'admin.abTestGroup': 'Grupo de Prueba A/B',
    'admin.enableNow': 'Activar Ahora',
    'admin.cancel': 'Cancelar',
    'admin.update': 'Actualizar',
    'admin.create': 'Crear',
    'admin.adList': 'Lista de Anuncios',
    'admin.analytics': 'Análisis',
    'admin.operationLogs': 'Registros de Operaciones',
    'admin.allAds': 'Todos los Anuncios',
    'admin.status': 'Estado',
    'admin.impressionsClicks': 'Impresiones/Clics',
    'admin.budgetSpent': 'Presupuesto/Gastado',
    'admin.actions': 'Acciones',
    'admin.active': 'Activo',
    'admin.disabled': 'Desactivado',
    'admin.loadFailed': 'Error al cargar anuncios',
    'admin.saveFailed': 'Error al guardar anuncio',
    'admin.updateSuccess': 'Anuncio actualizado exitosamente',
    'admin.createSuccess': 'Anuncio creado exitosamente',
    'admin.enableSuccess': 'Anuncio activado',
    'admin.disableSuccess': 'Anuncio desactivado',
    'admin.deleteConfirm': '¿Está seguro de eliminar este anuncio?',
    'admin.deleteSuccess': 'Anuncio eliminado exitosamente',
    'admin.deleteFailed': 'Error al eliminar',
    'admin.noPermission': 'Sin permiso',
    'admin.noAccess': 'Sin permiso de acceso',
    'admin.loading': 'Cargando...',
    
    // Common
    'common.welcome': 'Bienvenido de nuevo',
    'common.guestMode': 'Modo Invitado',
    'common.needLogin': 'Inicio de Sesión Requerido',
    'common.startMatch': 'Comenzar Partida',
    'common.startRank': 'Comenzar Clasificatorio',
    'common.backToHome': 'Volver al Inicio',
    'common.openSettings': 'Abrir Configuración de Juego',
    'common.enter': 'Entrar',
    'common.back': 'Volver',
    'common.copyright': 'Basado en las reglas modernas de Tetris',
    'common.confirm': 'Confirmar',
    'common.delete': 'Eliminar',
    'common.save': 'Guardar',
    'common.close': 'Cerrar',
    'common.success': 'Éxito',
    'common.failed': 'Fallido',
    'common.retry': 'Reintentar',
    'common.creating': 'Creando...',
    'common.loading': 'Cargando...',
    'common.comingSoon': 'Próximamente',
    'common.registeredUser': 'Usuario Registrado',
    'common.guestUser': 'Usuario Invitado',
    'common.loadStatsFailed': 'Error al cargar estadísticas',
    'common.networkError': 'Error de conexión de red',
    'common.modeFailed': 'Selección de modo fallida, intente de nuevo',
    
    // Tutorial
    'tutorial.title': 'Tutorial del Juego',
    'tutorial.description': 'Aprende técnicas avanzadas y estrategias',
    
    // Team Battle
    'teamBattle.title': 'Batalla en Equipo',
    'teamBattle.entryDesc': 'Batallas 2v2/3v3/4v4 con tres estrategias de basura',
    'teamBattle.createRoom': 'Crear Sala de Equipo',
    'teamBattle.joinRoom': 'Unirse a Sala',
    'teamBattle.activeRooms': 'Salas Activas',
    'teamBattle.strategy.focus': 'Ataque Concentrado',
    'teamBattle.strategy.random': 'Aleatorio',
    'teamBattle.strategy.even': 'Uniforme',
    'teamBattle.tabHint': 'Presiona Tab en la partida para cambiar estrategia',
    'teamBattle.teamSize': 'Tamaño del Equipo',
    'teamBattle.garbageStrategy': 'Estrategia de Distribución de Basura',
    'teamBattle.focusDesc': 'Ataque Concentrado - Enviar basura al oponente con mayor APM',
    'teamBattle.randomDesc': 'Aleatorio - Enviar basura aleatoriamente a cualquier oponente',
    'teamBattle.evenDesc': 'Uniforme - Distribuir basura uniformemente entre todos los oponentes',
    'teamBattle.unknownStrategy': 'Estrategia desconocida',
    'teamBattle.createSuccess': '¡Sala de equipo creada! Código: ',
    'teamBattle.joinSuccess': '¡Se unió exitosamente a la sala de equipo!',
    'teamBattle.noActiveRooms': 'No hay salas de equipo activas',
    'teamBattle.enter4DigitCode': 'Ingrese código de 4 dígitos',
    'teamBattle.setTeamAndStrategy': 'Configurar tamaño del equipo y estrategia de basura',
    'teamBattle.2v2': '2v2 (4 jugadores)',
    'teamBattle.3v3': '3v3 (6 jugadores)',
    'teamBattle.4v4': '4v4 (8 jugadores)',
    'teamBattle.2v2v2v2': '2v2/3v3/4v4 Batallas en Equipo',
    
    // Multiplayer
    'multiplayer.title': 'Multijugador',
    'multiplayer.1v1': 'Batalla 1v1',
    'multiplayer.1v1Desc': 'Batalla clásica uno contra uno de Tetris',
    'multiplayer.ranked': 'Clasificatorio',
    'multiplayer.rankedDesc': 'Participe en partidas clasificatorias y suba de rango',
    'multiplayer.customRoom': 'Sala Personalizada',
    'multiplayer.customRoomDesc': 'Cree o únase a salas de batalla personalizadas',
    'multiplayer.battleRoyale': 'Battle Royale',
    'multiplayer.battleRoyaleDesc': 'Batalla de múltiples jugadores, el último en pie gana',
    'multiplayer.botRoom': 'Batalla con Bot IA',
    'multiplayer.botRoomDesc': 'Batalla contra bots de IA de varias dificultades',
    'multiplayer.needLoginMulti': 'Se requiere inicio de sesión para multijugador',
    'multiplayer.quickLogin': 'Inicio Rápido como Invitado',
    
    // Bot Room
    'bot.createRoom': 'Crear Sala de Bot',
    'bot.createRoomDesc': 'Cree una sala de bot dedicada, agregue bots de IA de diferentes dificultades para practicar',
    'bot.availableRooms': 'Salas de Bot Disponibles',
    'bot.noRooms': 'No hay salas de bot disponibles',
    'bot.aboutRooms': 'Sobre las Salas de Bot',
    'bot.aboutDesc1': 'Las salas de bot son modos de juego para jugar contra bots de IA',
    'bot.aboutDesc2': 'Los bots en la sala se muestran como bloques rojos para fácil identificación',
    'bot.aboutDesc3': 'Soporta 4 niveles de dificultad: Fácil, Medio, Difícil, Experto',
    'bot.aboutDesc4': 'Puede jugar con múltiples bots y jugadores reales simultáneamente',
    'bot.aboutDesc5': 'Excelente para practicar habilidades y desafiar dificultades mayores',
    'bot.room': 'Sala de Bot',
    'bot.connected': 'Conectado',
    'bot.connecting': 'Conectando...',
    'bot.startGame': 'Iniciar Juego',
    'bot.creator': 'Creador',
    'bot.players': 'Jugadores',
    
    // Game Mode Selector
    'mode.select': 'Seleccionar Modo de Juego',
    'mode.backToMain': 'Volver al Menú Principal',
    'mode.target': 'Objetivo',
    'mode.timeLimit': 'Límite de Tiempo',
    'mode.unlimited': 'Juego Ilimitado',
    'mode.startGame': 'Iniciar Juego',
    'mode.timed': 'Cronometrado',
    'mode.sprint': 'Sprint',
    'mode.targetLines': 'Objetivo: {lines} líneas',
    'mode.timeLimitFormat': 'Tiempo: {time}',
    'mode.clearLines': 'Objetivo: Limpiar {lines} líneas'
  }
};

// Auto-detect language based on browser/location
const detectLanguage = (): Language => {
  const browserLang = navigator.language || navigator.languages?.[0] || 'en';
  const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
  
  if (browserLang.startsWith('zh')) {
    if (browserLang.includes('TW') || browserLang.includes('HK') || timezone.includes('Taipei')) {
      return 'zh-TW';
    }
    return 'zh';
  } else if (browserLang.startsWith('ja') || timezone.includes('Tokyo')) {
    return 'ja';
  } else if (browserLang.startsWith('ko') || timezone.includes('Seoul')) {
    return 'ko';
  } else if (browserLang.startsWith('es')) {
    return 'es';
  }
  
  return 'en';
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage);
    } else {
      setLanguage('en');
      localStorage.setItem('language', 'en');
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
