import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'zh' | 'zh-TW' | 'en' | 'ja' | 'ko' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  zh: {
    'game.title': '俄罗斯方块竞技平台',
    'game.play': '开始游戏',
    'game.singlePlayer': '单人模式',
    'game.multiPlayer': '多人模式',
    'game.ranked': '排位赛',
    'game.sprint40': '40行竞速',
    'game.ultra2min': '2分钟极限',
    'game.endless': '无尽模式',
    'game.freeForAll': '自由对战',
    'game.oneVsOne': '1v1对战',
    'game.customRoom': '自建房间',
    'auth.login': '登录',
    'auth.register': '注册',
    'auth.guest': '游客模式',
    'auth.username': '用户名',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'settings.controls': '控制设置',
    'settings.keyboard': '键盘设置',
    'settings.game': '游戏设置',
    'settings.shortcuts': '快捷方式',
    'settings.das': '键盘重复速率',
    'settings.arr': '软降速度',
    'settings.sdf': '瞬降速度',
    'settings.preview': '预设布局',
    'settings.customKeys': '自定义键位',
    'settings.moveLeft': '左移',
    'settings.moveRight': '右移',
    'settings.softDrop': '软降',
    'settings.hardDrop': '硬降',
    'settings.rotateClockwise': '顺时针旋转',
    'settings.rotateCounterclockwise': '逆时针旋转',
    'settings.rotate180': '180°旋转',
    'settings.hold': '暂存',
    'settings.pause': '暂停',
    'settings.keyboardInstructions': '按键映射说明',
    'settings.keyboardTip': '点击按键框然后按下你想要的按键来设置',
    'room.create': '创建房间',
    'room.join': '加入房间',
    'room.share': '分享房间',
    'room.maxPlayers': '最大玩家数',
    'replay.view': '查看回放',
    'replay.speed': '回放速度',
    'nav.home': '首页',
    'nav.play': '游戏',
    'nav.multiplayer': '多人游戏',
    'nav.profile': '个人资料',
    'nav.leaderboard': '排行榜',
    'nav.settings': '设置',
    'rank.system': '排位系统',
    'rank.current': '当前段位',
    'rank.points': '积分',
    'rank.nextRank': '下一段位',
    'rank.promotion': '还需积分晋级',
    'ad.placeholder': '广告位招租中',
    'ad.contact': '联系管理员',
    'income.donations': '捐赠收入',
    'income.ads': '广告收入',
    'income.total': '总收入',
    'admin.panel': '管理后台',
    'admin.income': '收入系统',
    'common.welcome': '欢迎回来',
    'common.guestMode': '游客模式',
    'common.needLogin': '需要登录',
    'common.startMatch': '开始匹配',
    'common.startRank': '开始排位',
    'common.backToHome': '返回首页',
    'common.openSettings': '打开游戏设置',
    'common.enter': '进入',
    'common.back': '返回',
    'tutorial.title': '游戏教程',
    'tutorial.description': '学习高级技巧和策略',
    'replay.title': '回放系统',
    'replay.description': '观看和分析游戏录像',
    'admin.title': '后台管理',
    'admin.description': '广告和收入管理',
    'game.description': '体验最纯粹的俄罗斯方块竞技',
    'game.singlePlayerDesc': '挑战自己的极限，刷新个人记录',
    'game.multiPlayerDesc': '与全球玩家实时对战',
    'game.rankedDesc': '争夺最高段位排名',
    'settings.controlsDesc': '自定义按键和游戏参数',
    'common.copyright': '基于现代俄罗斯方块规则'
  },
  'zh-TW': {
    'game.title': '俄羅斯方塊競技平台',
    'game.play': '開始遊戲',
    'game.singlePlayer': '單人模式',
    'game.multiPlayer': '多人模式',
    'game.ranked': '排位賽',
    'game.sprint40': '40行競速',
    'game.ultra2min': '2分鐘極限',
    'game.endless': '無盡模式',
    'game.freeForAll': '自由對戰',
    'game.oneVsOne': '1v1對戰',
    'game.customRoom': '自建房間',
    'auth.login': '登入',
    'auth.register': '註冊',
    'auth.guest': '訪客模式',
    'auth.username': '用戶名',
    'auth.email': '郵箱',
    'auth.password': '密碼',
    'settings.controls': '控制設定',
    'settings.keyboard': '鍵盤設定',
    'settings.game': '遊戲設定',
    'settings.shortcuts': '快捷方式',
    'settings.das': '鍵盤重複速率',
    'settings.arr': '軟降速度',
    'settings.sdf': '瞬降速度',
    'settings.preview': '預設佈局',
    'settings.customKeys': '自定義鍵位',
    'settings.moveLeft': '左移',
    'settings.moveRight': '右移',
    'settings.softDrop': '軟降',
    'settings.hardDrop': '硬降',
    'settings.rotateClockwise': '順時針旋轉',
    'settings.rotateCounterclockwise': '逆時針旋轉',
    'settings.rotate180': '180°旋轉',
    'settings.hold': '暫存',
    'settings.pause': '暫停',
    'settings.keyboardInstructions': '按鍵映射說明',
    'settings.keyboardTip': '點擊按鍵框然後按下你想要的按鍵來設定',
    'room.create': '創建房間',
    'room.join': '加入房間',
    'room.share': '分享房間',
    'room.maxPlayers': '最大玩家數',
    'replay.view': '查看回放',
    'replay.speed': '回放速度',
    'nav.home': '首頁',
    'nav.play': '遊戲',
    'nav.multiplayer': '多人遊戲',
    'nav.profile': '個人資料',
    'nav.leaderboard': '排行榜',
    'nav.settings': '設定',
    'rank.system': '排位系統',
    'rank.current': '當前段位',
    'rank.points': '積分',
    'rank.nextRank': '下一段位',
    'rank.promotion': '還需積分晉級',
    'ad.placeholder': '廣告位招租中',
    'ad.contact': '聯繫管理員',
    'income.donations': '捐贈收入',
    'income.ads': '廣告收入',
    'income.total': '總收入',
    'admin.panel': '管理後台',
    'admin.income': '收入系統',
    'common.welcome': '歡迎回來',
    'common.guestMode': '訪客模式',
    'common.needLogin': '需要登入',
    'common.startMatch': '開始匹配',
    'common.startRank': '開始排位',
    'common.backToHome': '返回首頁',
    'common.openSettings': '打開遊戲設定',
    'tutorial.title': '遊戲教程',
    'tutorial.description': '學習高級技巧和策略',
    'replay.title': '回放系統',
    'replay.description': '觀看和分析遊戲錄像',
    'admin.title': '後台管理',
    'admin.description': '廣告和收入管理',
    'game.description': '體驗最純粹的俄羅斯方塊競技',
    'game.singlePlayerDesc': '挑戰自己的極限，刷新個人記錄',
    'game.multiPlayerDesc': '與全球玩家實時對戰',
    'game.rankedDesc': '爭奪最高段位排名',
    'settings.controlsDesc': '自定義按鍵和遊戲參數',
    'common.copyright': '基於現代俄羅斯方塊規則'
  },
  en: {
    'game.title': 'Tetris Gaming Platform',
    'game.play': 'Start Playing',
    'game.singlePlayer': 'Single Player',
    'game.multiPlayer': 'Multiplayer',
    'game.ranked': 'Ranked',
    'game.sprint40': '40 Lines Sprint',
    'game.ultra2min': '2 Minute Ultra',
    'game.endless': 'Endless Mode',
    'game.freeForAll': 'Free For All',
    'game.oneVsOne': '1v1 Battle',
    'game.customRoom': 'Custom Room',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.guest': 'Guest Mode',
    'auth.username': 'Username',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'settings.controls': 'Controls',
    'settings.keyboard': 'Keyboard Settings',
    'settings.game': 'Game Settings',
    'settings.shortcuts': 'Shortcuts',
    'settings.das': 'DAS Rate',
    'settings.arr': 'ARR Speed',
    'settings.sdf': 'SDF Speed',
    'settings.preview': 'Preset Layout',
    'settings.customKeys': 'Custom Keys',
    'settings.moveLeft': 'Move Left',
    'settings.moveRight': 'Move Right',
    'settings.softDrop': 'Soft Drop',
    'settings.hardDrop': 'Hard Drop',
    'settings.rotateClockwise': 'Rotate Clockwise',
    'settings.rotateCounterclockwise': 'Rotate Counterclockwise',
    'settings.rotate180': '180° Rotation',
    'settings.hold': 'Hold',
    'settings.pause': 'Pause',
    'settings.keyboardInstructions': 'Key Mapping Instructions',
    'settings.keyboardTip': 'Click on the key box and press the key you want to set',
    'room.create': 'Create Room',
    'room.join': 'Join Room',
    'room.share': 'Share Room',
    'room.maxPlayers': 'Max Players',
    'replay.view': 'View Replay',
    'replay.speed': 'Replay Speed',
    'nav.home': 'Home',
    'nav.play': 'Play',
    'nav.multiplayer': 'Multiplayer',
    'nav.profile': 'Profile',
    'nav.leaderboard': 'Leaderboard',
    'nav.settings': 'Settings',
    'rank.system': 'Ranking System',
    'rank.current': 'Current Rank',
    'rank.points': 'Points',
    'rank.nextRank': 'Next Rank',
    'rank.promotion': 'Points needed for promotion',
    'ad.placeholder': 'Advertisement Space Available',
    'ad.contact': 'Contact Admin',
    'income.donations': 'Donation Income',
    'income.ads': 'Ad Revenue',
    'income.total': 'Total Income',
    'admin.panel': 'Admin Panel',
    'admin.income': 'Income System',
    'common.welcome': 'Welcome back',
    'common.guestMode': 'Guest Mode',
    'common.needLogin': 'Login Required',
    'common.startMatch': 'Start Match',
    'common.startRank': 'Start Ranked',
    'common.backToHome': 'Back to Home',
    'common.openSettings': 'Open Game Settings',
    'common.enter': 'Enter',
    'common.back': 'Back',
    'tutorial.title': 'Game Tutorial',
    'tutorial.description': 'Learn advanced techniques and strategies',
    'replay.title': 'Replay System',
    'replay.description': 'Watch and analyze game recordings',
    'admin.title': 'Admin Panel',
    'admin.description': 'Advertising and revenue management',
    'game.description': 'Experience the purest Tetris competition',
    'game.singlePlayerDesc': 'Challenge your limits and break personal records',
    'game.multiPlayerDesc': 'Real-time battles with global players',
    'game.rankedDesc': 'Compete for the highest rank',
    'settings.controlsDesc': 'Customize keys and game parameters',
    'common.copyright': 'Based on modern Tetris rules'
  },
  ja: {
    'game.title': 'テトリスゲーミングプラットフォーム',
    'game.play': 'ゲーム開始',
    'game.singlePlayer': 'シングルプレイ',
    'game.multiPlayer': 'マルチプレイ',
    'game.ranked': 'ランクマッチ',
    'game.sprint40': '40ライン',
    'game.ultra2min': '2分間ウルトラ',
    'game.endless': 'エンドレス',
    'game.freeForAll': 'フリーフォーオール',
    'game.oneVsOne': '1対1バトル',
    'game.customRoom': 'カスタムルーム',
    'auth.login': 'ログイン',
    'auth.register': '登録',
    'auth.guest': 'ゲストモード',
    'auth.username': 'ユーザー名',
    'auth.email': 'メール',
    'auth.password': 'パスワード',
    'settings.controls': 'コントロール',
    'settings.keyboard': 'キーボード設定',
    'settings.game': 'ゲーム設定',
    'settings.shortcuts': 'ショートカット',
    'settings.das': 'DAS速度',
    'settings.arr': 'ARR速度',
    'settings.sdf': 'SDF速度',
    'settings.preview': 'プリセットレイアウト',
    'settings.customKeys': 'カスタムキー',
    'settings.moveLeft': '左移動',
    'settings.moveRight': '右移動',
    'settings.softDrop': 'ソフトドロップ',
    'settings.hardDrop': 'ハードドロップ',
    'settings.rotateClockwise': '時計回り回転',
    'settings.rotateCounterclockwise': '反時計回り回転',
    'settings.rotate180': '180度回転',
    'settings.hold': 'ホールド',
    'settings.pause': '一時停止',
    'settings.keyboardInstructions': 'キーマッピング説明',
    'settings.keyboardTip': 'キーボックスをクリックして設定したいキーを押してください',
    'room.create': 'ルーム作成',
    'room.join': 'ルーム参加',
    'room.share': 'ルーム共有',
    'room.maxPlayers': '最大プレイヤー数',
    'replay.view': 'リプレイ表示',
    'replay.speed': 'リプレイ速度',
    'nav.home': 'ホーム',
    'nav.play': 'プレイ',
    'nav.multiplayer': 'マルチプレイ',
    'nav.profile': 'プロフィール',
    'nav.leaderboard': 'リーダーボード',
    'nav.settings': '設定',
    'rank.system': 'ランキングシステム',
    'rank.current': '現在のランク',
    'rank.points': 'ポイント',
    'rank.nextRank': '次のランク',
    'rank.promotion': '昇格に必要なポイント',
    'ad.placeholder': '広告スペース利用可能',
    'ad.contact': '管理者に連絡',
    'income.donations': '寄付収入',
    'income.ads': '広告収入',
    'income.total': '総収入',
    'admin.panel': '管理パネル',
    'admin.income': '収入システム',
    'common.welcome': 'おかえりなさい',
    'common.guestMode': 'ゲストモード',
    'common.needLogin': 'ログインが必要',
    'common.startMatch': 'マッチ開始',
    'common.startRank': 'ランク開始',
    'common.backToHome': 'ホームに戻る',
    'common.openSettings': 'ゲーム設定を開く',
    'tutorial.title': 'ゲームチュートリアル',
    'tutorial.description': '高度なテクニックと戦略を学ぶ',
    'replay.title': 'リプレイシステム',
    'replay.description': 'ゲーム録画を見て分析する',
    'admin.title': '管理パネル',
    'admin.description': '広告と収入管理',
    'game.description': '最も純粋なテトリス競技を体験',
    'game.singlePlayerDesc': '自分の限界に挑戦し、個人記録を更新',
    'game.multiPlayerDesc': '世界中のプレイヤーとリアルタイムバトル',
    'game.rankedDesc': '最高ランクを目指して競争',
    'settings.controlsDesc': 'キーとゲームパラメータをカスタマイズ',
    'common.copyright': '現代テトリスルールに基づく'
  },
  ko: {
    'game.title': '테트리스 게이밍 플랫폼',
    'game.play': '게임 시작',
    'game.singlePlayer': '싱글 플레이어',
    'game.multiPlayer': '멀티 플레이어',
    'game.ranked': '랭크전',
    'game.sprint40': '40라인 스프린트',
    'game.ultra2min': '2분 울트라',
    'game.endless': '무한 모드',
    'game.freeForAll': '자유 대전',
    'game.oneVsOne': '1대1 배틀',
    'game.customRoom': '커스텀 룸',
    'auth.login': '로그인',
    'auth.register': '회원가입',
    'auth.guest': '게스트 모드',
    'auth.username': '사용자명',
    'auth.email': '이메일',
    'auth.password': '비밀번호',
    'settings.controls': '컨트롤',
    'settings.keyboard': '키보드 설정',
    'settings.game': '게임 설정',
    'settings.shortcuts': '바로가기',
    'settings.das': 'DAS 속도',
    'settings.arr': 'ARR 속도',
    'settings.sdf': 'SDF 속도',
    'settings.preview': '프리셋 레이아웃',
    'settings.customKeys': '커스텀 키',
    'settings.moveLeft': '왼쪽 이동',
    'settings.moveRight': '오른쪽 이동',
    'settings.softDrop': '소프트 드롭',
    'settings.hardDrop': '하드 드롭',
    'settings.rotateClockwise': '시계방향 회전',
    'settings.rotateCounterclockwise': '반시계방향 회전',
    'settings.rotate180': '180도 회전',
    'settings.hold': '홀드',
    'settings.pause': '일시정지',
    'settings.keyboardInstructions': '키 매핑 설명',
    'settings.keyboardTip': '키 박스를 클릭하고 설정하고 싶은 키를 누르세요',
    'room.create': '룸 생성',
    'room.join': '룸 참가',
    'room.share': '룸 공유',
    'room.maxPlayers': '최대 플레이어',
    'replay.view': '리플레이 보기',
    'replay.speed': '리플레이 속도',
    'nav.home': '홈',
    'nav.play': '플레이',
    'nav.multiplayer': '멀티플레이어',
    'nav.profile': '프로필',
    'nav.leaderboard': '리더보드',
    'nav.settings': '설정',
    'rank.system': '랭킹 시스템',
    'rank.current': '현재 랭크',
    'rank.points': '포인트',
    'rank.nextRank': '다음 랭크',
    'rank.promotion': '승급 필요 포인트',
    'ad.placeholder': '광고 공간 사용 가능',
    'ad.contact': '관리자 연락',
    'income.donations': '기부 수입',
    'income.ads': '광고 수입',
    'income.total': '총 수입',
    'admin.panel': '관리자 패널',
    'admin.income': '수입 시스템',
    'common.welcome': '다시 오신 것을 환영합니다',
    'common.guestMode': '게스트 모드',
    'common.needLogin': '로그인 필요',
    'common.startMatch': '매치 시작',
    'common.startRank': '랭크 시작',
    'common.backToHome': '홈으로 돌아가기',
    'common.openSettings': '게임 설정 열기',
    'tutorial.title': '게임 튜토리얼',
    'tutorial.description': '고급 기술과 전략 배우기',
    'replay.title': '리플레이 시스템',
    'replay.description': '게임 녹화 시청 및 분석',
    'admin.title': '관리자 패널',
    'admin.description': '광고 및 수익 관리',
    'game.description': '가장 순수한 테트리스 경쟁 경험',
    'game.singlePlayerDesc': '자신의 한계에 도전하고 개인 기록 갱신',
    'game.multiPlayerDesc': '전 세계 플레이어와 실시간 배틀',
    'game.rankedDesc': '최고 랭크를 위한 경쟁',
    'settings.controlsDesc': '키와 게임 매개변수 커스터마이징',
    'common.copyright': '현대 테트리스 규칙 기반'
  },
  es: {
    'game.title': 'Plataforma de Gaming Tetris',
    'game.play': 'Comenzar Juego',
    'game.singlePlayer': 'Un Jugador',
    'game.multiPlayer': 'Multijugador',
    'game.ranked': 'Clasificatorio',
    'game.sprint40': 'Sprint 40 Líneas',
    'game.ultra2min': 'Ultra 2 Minutos',
    'game.endless': 'Modo Infinito',
    'game.freeForAll': 'Todos contra Todos',
    'game.oneVsOne': 'Batalla 1v1',
    'game.customRoom': 'Sala Personalizada',
    'auth.login': 'Iniciar Sesión',
    'auth.register': 'Registrarse',
    'auth.guest': 'Modo Invitado',
    'auth.username': 'Nombre de Usuario',
    'auth.email': 'Correo Electrónico',
    'auth.password': 'Contraseña',
    'settings.controls': 'Controles',
    'settings.keyboard': 'Configuración de Teclado',
    'settings.game': 'Configuración de Juego',
    'settings.shortcuts': 'Atajos',
    'settings.das': 'Velocidad DAS',
    'settings.arr': 'Velocidad ARR',
    'settings.sdf': 'Velocidad SDF',
    'settings.preview': 'Diseño Preestablecido',
    'settings.customKeys': 'Teclas Personalizadas',
    'settings.moveLeft': 'Mover Izquierda',
    'settings.moveRight': 'Mover Derecha',
    'settings.softDrop': 'Caída Suave',
    'settings.hardDrop': 'Caída Dura',
    'settings.rotateClockwise': 'Rotar Horario',
    'settings.rotateCounterclockwise': 'Rotar Antihorario',
    'settings.rotate180': 'Rotación 180°',
    'settings.hold': 'Retener',
    'settings.pause': 'Pausa',
    'settings.keyboardInstructions': 'Instrucciones de Mapeo de Teclas',
    'settings.keyboardTip': 'Haz clic en la caja de tecla y presiona la tecla que quieres configurar',
    'room.create': 'Crear Sala',
    'room.join': 'Unirse a Sala',
    'room.share': 'Compartir Sala',
    'room.maxPlayers': 'Máximo de Jugadores',
    'replay.view': 'Ver Repetición',
    'replay.speed': 'Velocidad de Repetición',
    'nav.home': 'Inicio',
    'nav.play': 'Jugar',
    'nav.multiplayer': 'Multijugador',
    'nav.profile': 'Perfil',
    'nav.leaderboard': 'Tabla de Líderes',
    'nav.settings': 'Configuración',
    'rank.system': 'Sistema de Clasificación',
    'rank.current': 'Rango Actual',
    'rank.points': 'Puntos',
    'rank.nextRank': 'Siguiente Rango',
    'rank.promotion': 'Puntos necesarios para promoción',
    'ad.placeholder': 'Espacio Publicitario Disponible',
    'ad.contact': 'Contactar Administrador',
    'income.donations': 'Ingresos por Donaciones',
    'income.ads': 'Ingresos por Publicidad',
    'income.total': 'Ingresos Totales',
    'admin.panel': 'Panel de Administración',
    'admin.income': 'Sistema de Ingresos',
    'common.welcome': 'Bienvenido de nuevo',
    'common.guestMode': 'Modo Invitado',
    'common.needLogin': 'Inicio de Sesión Requerido',
    'common.startMatch': 'Comenzar Partida',
    'common.startRank': 'Comenzar Clasificatorio',
    'common.backToHome': 'Volver al Inicio',
    'common.openSettings': 'Abrir Configuración de Juego',
    'tutorial.title': 'Tutorial del Juego',
    'tutorial.description': 'Aprende técnicas avanzadas y estrategias',
    'replay.title': 'Sistema de Repetición',
    'replay.description': 'Ver y analizar grabaciones de juego',
    'admin.title': 'Panel de Administración',
    'admin.description': 'Gestión de publicidad e ingresos',
    'game.description': 'Experimenta la competición de Tetris más pura',
    'game.singlePlayerDesc': 'Desafía tus límites y rompe récords personales',
    'game.multiPlayerDesc': 'Batallas en tiempo real con jugadores globales',
    'game.rankedDesc': 'Compite por el rango más alto',
    'settings.controlsDesc': 'Personalizar teclas y parámetros de juego',
    'common.copyright': 'Basado en las reglas modernas de Tetris'
  }
};

// Auto-detect language based on browser/location
const detectLanguage = (): Language => {
  // Try to get user's preferred language from browser
  const browserLang = navigator.language || navigator.languages?.[0] || 'en';
  
  // Try to detect region from timezone (approximate)
  const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
  
  // Map browser language codes to our supported languages
  if (browserLang.startsWith('zh')) {
    if (browserLang.includes('TW') || browserLang.includes('HK') || timezone.includes('Taipei')) {
      return 'zh-TW';
    }
    return 'zh';
  } else if (browserLang.startsWith('ja') || timezone.includes('Tokyo')) {
    return 'ja';
  } else if (browserLang.startsWith('ko') || timezone.includes('Seoul')) {
    return 'ko';
  } else if (browserLang.startsWith('es')) {
    return 'es';
  }
  
  // Default to English for unknown regions
  return 'en';
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage);
    } else {
      // Set English as default language on first visit
      setLanguage('en');
      localStorage.setItem('language', 'en');
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
