// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://wcwnyvoezudyxiayyzek.supabase.co"
const supabaseAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indjd255dm9lenVkeXhpYXl5emVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MTkxNTUsImV4cCI6MjA2NjM5NTE1NX0.uqrT2Ry_WuzlGS-5pq0VgK97jLom3xJS69g2PSbtLiQ"

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  global: {
    headers: {
      'X-Client-Info': 'supabase-js-web',
    },
  },
  realtime: {
    params: {
      eventsPerSecond: 2,
    },
    heartbeatIntervalMs: 30000,
    reconnectAfterMs: (attempts: number) => Math.min(attempts * 1000, 10000),
  },
  db: {
    schema: 'public',
  },
})

// 添加网络错误处理
// Note: The supabase client handles network errors internally
// If custom error handling is needed, use interceptors on specific requests