// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcwnyvoezudyxiayyzek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indjd255dm9lenVkeXhpYXl5emVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MTkxNTUsImV4cCI6MjA2NjM5NTE1NX0.uqrT2Ry_WuzlGS-5pq0VgK97jLom3xJS69g2PSbtLiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);